export const states = [
    { value: 'AF', label: 'Afghanistan' },
    { value: 'AX', label: 'Åland Islands' },
    { value: 'AL', label: 'Albania' },
    { value: 'DZ', label: 'Algeria' },
    { value: 'AS', label: 'American Samoa' },
    { value: 'AD', label: 'Andorra' },
    { value: 'AO', label: 'Angola' },
    { value: 'AI', label: 'Anguilla' },
    { value: 'AG', label: 'Antigua and Barbuda' },
    { value: 'AR', label: 'Argentina' },
    { value: 'AM', label: 'Armenia' },
    { value: 'AW', label: 'Aruba' },
    { value: 'AU', label: 'Australia' },
    { value: 'AT', label: 'Austria' },
    { value: 'AZ', label: 'Azerbaijan' },
    { value: 'BS', label: 'Bahamas' },
    { value: 'BH', label: 'Bahrain' },
    { value: 'BD', label: 'Bangladesh' },
    { value: 'BB', label: 'Barbados' },
    { value: 'BY', label: 'Belarus' },
    { value: 'BE', label: 'Belgium' },
    { value: 'BZ', label: 'Belize' },
    { value: 'BJ', label: 'Benin' },
    { value: 'BM', label: 'Bermuda' },
    { value: 'BT', label: 'Bhutan' },
    { value: 'BO', label: 'Bolivia' },
    { value: 'BA', label: 'Bosnia and Herzegovina' },
    { value: 'BW', label: 'Botswana' },
    { value: 'BR', label: 'Brazil' },
    { value: 'BN', label: 'Brunei Darussalam' },
    { value: 'BG', label: 'Bulgaria' },
    { value: 'BF', label: 'Burkina Faso' },
    { value: 'BI', label: 'Burundi' },
    { value: 'CV', label: 'Cabo Verde' },
    { value: 'KH', label: 'Cambodia' },
    { value: 'CM', label: 'Cameroon' },
    { value: 'CA', label: 'Canada' },
    { value: 'KY', label: 'Cayman Islands' },
    { value: 'CF', label: 'Central African Republic' },
    { value: 'TD', label: 'Chad' },
    { value: 'CL', label: 'Chile' },
    { value: 'CN', label: 'China' },
    { value: 'CO', label: 'Colombia' },
    { value: 'KM', label: 'Comoros' },
    { value: 'CG', label: 'Congo' },
    { value: 'CD', label: 'Congo, the Democratic Republic of the' },
    { value: 'CR', label: 'Costa Rica' },
    { value: 'CI', label: "Côte d'Ivoire" },
    { value: 'HR', label: 'Croatia' },
    { value: 'CU', label: 'Cuba' },
    { value: 'CY', label: 'Cyprus' },
    { value: 'CZ', label: 'Czechia' },
    { value: 'DK', label: 'Denmark' },
    { value: 'DJ', label: 'Djibouti' },
    { value: 'DM', label: 'Dominica' },
    { value: 'DO', label: 'Dominican Republic' },
    { value: 'EC', label: 'Ecuador' },
    { value: 'EG', label: 'Egypt' },
    { value: 'SV', label: 'El Salvador' },
    { value: 'GQ', label: 'Equatorial Guinea' },
    { value: 'ER', label: 'Eritrea' },
    { value: 'EE', label: 'Estonia' },
    { value: 'SZ', label: 'Eswatini' },
    { value: 'ET', label: 'Ethiopia' },
    { value: 'FJ', label: 'Fiji' },
    { value: 'FI', label: 'Finland' },
    { value: 'FR', label: 'France' },
    { value: 'GA', label: 'Gabon' },
    { value: 'GM', label: 'Gambia' },
    { value: 'GE', label: 'Georgia' },
    { value: 'DE', label: 'Germany' },
    { value: 'GH', label: 'Ghana' },
    { value: 'GI', label: 'Gibraltar' },
    { value: 'GR', label: 'Greece' },
    { value: 'GL', label: 'Greenland' },
    { value: 'GD', label: 'Grenada' },
    { value: 'GP', label: 'Guadeloupe' },
    { value: 'GU', label: 'Guam' },
    { value: 'GT', label: 'Guatemala' },
    { value: 'GN', label: 'Guinea' },
    { value: 'GW', label: 'Guinea-Bissau' },
    { value: 'GY', label: 'Guyana' },
    { value: 'HT', label: 'Haiti' },
    { value: 'HN', label: 'Honduras' },
    { value: 'HK', label: 'Hong Kong' },
    { value: 'HU', label: 'Hungary' },
    { value: 'IS', label: 'Iceland' },
    { value: 'IN', label: 'India' },
    { value: 'ID', label: 'Indonesia' },
    { value: 'IR', label: 'Iran' },
    { value: 'IQ', label: 'Iraq' },
    { value: 'IE', label: 'Ireland' },
    { value: 'IM', label: 'Isle of Man' },
    { value: 'IL', label: 'Israel' },
    { value: 'IT', label: 'Italy' },
    { value: 'JM', label: 'Jamaica' },
    { value: 'JP', label: 'Japan' },
    { value: 'JE', label: 'Jersey' },
    { value: 'JO', label: 'Jordan' },
    { value: 'KZ', label: 'Kazakhstan' },
    { value: 'KE', label: 'Kenya' },
    { value: 'KI', label: 'Kiribati' },
    { value: 'KP', label: "Korea, Democratic People's Republic of" },
    { value: 'KR', label: 'Korea, Republic of' },
    { value: 'KW', label: 'Kuwait' },
    { value: 'KG', label: 'Kyrgyzstan' },
    { value: 'LA', label: 'Laos' },
    { value: 'LV', label: 'Latvia' },
    { value: 'LB', label: 'Lebanon' },
    { value: 'LS', label: 'Lesotho' },
    { value: 'LR', label: 'Liberia' },
    { value: 'LY', label: 'Libya' },
    { value: 'LI', label: 'Liechtenstein' },
    { value: 'LT', label: 'Lithuania' },
    { value: 'LU', label: 'Luxembourg' },
    { value: 'MG', label: 'Madagascar' },
    { value: 'MW', label: 'Malawi' },
    { value: 'MY', label: 'Malaysia' },
    { value: 'MV', label: 'Maldives' },
    { value: 'ML', label: 'Mali' },
    { value: 'MT', label: 'Malta' },
    { value: 'MH', label: 'Marshall Islands' },
    { value: 'MQ', label: 'Martinique' },
    { value: 'MR', label: 'Mauritania' },
    { value: 'MU', label: 'Mauritius' },
    { value: 'YT', label: 'Mayotte' },
    { value: 'MX', label: 'Mexico' },
    { value: 'FM', label: 'Micronesia, Federated States of' },
    { value: 'MD', label: 'Moldova, Republic of' },
    { value: 'MC', label: 'Monaco' },
    { value: 'MN', label: 'Mongolia' },
    { value: 'ME', label: 'Montenegro' },
    { value: 'MS', label: 'Montserrat' },
    { value: 'MA', label: 'Morocco' },
    { value: 'MZ', label: 'Mozambique' },
    { value: 'MM', label: 'Myanmar' },
    { value: 'NA', label: 'Namibia' },
    { value: 'NR', label: 'Nauru' },
    { value: 'NP', label: 'Nepal' },
    { value: 'NL', label: 'Netherlands' },
    { value: 'NC', label: 'New Caledonia' },
    { value: 'NZ', label: 'New Zealand' },
    { value: 'NI', label: 'Nicaragua' },
    { value: 'NE', label: 'Niger' },
    { value: 'NG', label: 'Nigeria' },
    { value: 'NU', label: 'Niue' },
    { value: 'NF', label: 'Norfolk Island' },
    { value: 'MK', label: 'North Macedonia' },
    { value: 'MP', label: 'Northern Mariana Islands' },
    { value: 'NO', label: 'Norway' },
    { value: 'OM', label: 'Oman' },
    { value: 'PK', label: 'Pakistan' },
    { value: 'PW', label: 'Palau' },
    { value: 'PS', label: 'Palestine, State of' },
    { value: 'PA', label: 'Panama' },
    { value: 'PG', label: 'Papua New Guinea' },
    { value: 'PY', label: 'Paraguay' },
    { value: 'PE', label: 'Peru' },
    { value: 'PH', label: 'Philippines' },
    { value: 'PN', label: 'Pitcairn' },
    { value: 'PL', label: 'Poland' },
    { value: 'PT', label: 'Portugal' },
    { value: 'PR', label: 'Puerto Rico' },
    { value: 'QA', label: 'Qatar' },
    { value: 'RO', label: 'Romania' },
    { value: 'RU', label: 'Russian Federation' },
    { value: 'RW', label: 'Rwanda' },
    { value: 'RE', label: 'Réunion' },
    { value: 'BL', label: 'Saint Barthélemy' },
    { value: 'SH', label: 'Saint Helena, Ascension and Tristan da Cunha' },
    { value: 'KN', label: 'Saint Kitts and Nevis' },
    { value: 'LC', label: 'Saint Lucia' },
    { value: 'MF', label: 'Saint Martin (French part)' },
    { value: 'PM', label: 'Saint Pierre and Miquelon' },
    { value: 'VC', label: 'Saint Vincent and the Grenadines' },
    { value: 'WS', label: 'Samoa' },
    { value: 'SM', label: 'San Marino' },
    { value: 'ST', label: 'Sao Tome and Principe' },
    { value: 'SA', label: 'Saudi Arabia' },
    { value: 'SN', label: 'Senegal' },
    { value: 'RS', label: 'Serbia' },
    { value: 'SC', label: 'Seychelles' },
    { value: 'SL', label: 'Sierra Leone' },
    { value: 'SG', label: 'Singapore' },
    { value: 'SX', label: 'Sint Maarten (Dutch part)' },
    { value: 'SK', label: 'Slovakia' },
    { value: 'SI', label: 'Slovenia' },
    { value: 'SB', label: 'Solomon Islands' },
    { value: 'SO', label: 'Somalia' },
    { value: 'ZA', label: 'South Africa' },
    { value: 'GS', label: 'South Georgia and the South Sandwich Islands' },
    { value: 'SS', label: 'South Sudan' },
    { value: 'ES', label: 'Spain' },
    { value: 'LK', label: 'Sri Lanka' },
    { value: 'SD', label: 'Sudan' },
    { value: 'SR', label: 'Suriname' },
    { value: 'SZ', label: 'Svalbard and Jan Mayen' },
    { value: 'SE', label: 'Sweden' },
    { value: 'CH', label: 'Switzerland' },
    { value: 'SY', label: 'Syrian Arab Republic' },
    { value: 'TW', label: 'Taiwan' },
    { value: 'TJ', label: 'Tajikistan' },
    { value: 'TZ', label: 'Tanzania, United Republic of' },
    { value: 'TH', label: 'Thailand' },
    { value: 'TL', label: 'Timor-Leste' },
    { value: 'TG', label: 'Togo' },
    { value: 'TK', label: 'Tokelau' },
    { value: 'TO', label: 'Tonga' },
    { value: 'TT', label: 'Trinidad and Tobago' },
    { value: 'TN', label: 'Tunisia' },
    { value: 'TR', label: 'Turkey' },
    { value: 'TM', label: 'Turkmenistan' },
    { value: 'TC', label: 'Turks and Caicos Islands' },
    { value: 'TV', label: 'Tuvalu' },
    { value: 'UG', label: 'Uganda' },
    { value: 'UA', label: 'Ukraine' },
    { value: 'AE', label: 'United Arab Emirates' },
    { value: 'GB', label: 'United Kingdom' },
    { value: 'US', label: 'United States of America' },
    { value: 'UM', label: 'United States Minor Outlying Islands' },
    { value: 'VI', label: 'United States Virgin Islands' },
    { value: 'UY', label: 'Uruguay' },
    { value: 'UZ', label: 'Uzbekistan' },
    { value: 'VU', label: 'Vanuatu' },
    { value: 'VE', label: 'Venezuela' },
    { value: 'VN', label: 'Viet Nam' },
    { value: 'WF', label: 'Wallis and Futuna' },
    { value: 'EH', label: 'Western Sahara' },
    { value: 'YE', label: 'Yemen' },
    { value: 'ZM', label: 'Zambia' },
    { value: 'ZW', label: 'Zimbabwe' },
  ];
  
  export const cities = {
    // Afganistán
    AF: [
      { value: 'KAB', label: 'Kabul' },
      { value: 'KANDA', label: 'Kandahar' },
      { value: 'HER', label: 'Herat' },
      { value: 'NAZ', label: 'Nangarhar' },
      { value: 'BAG', label: 'Baghlan' },
      { value: 'BAD', label: 'Badakhshan' },
      { value: 'KAP', label: 'Kabul' },
      { value: 'SAM', label: 'Samangan' },
      { value: 'GHAZ', label: 'Ghazni' },
      { value: 'KUN', label: 'Kunduz' },
      { value: 'LAG', label: 'Laghman' },
      { value: 'DAY', label: 'Daykundi' },
      { value: 'PAK', label: 'Paktia' },
      { value: 'WAZ', label: 'Waziristan' },
      { value: 'NIM', label: 'Nimroz' },
      { value: 'KHOST', label: 'Khost' },
      { value: 'URZ', label: 'Urozgan' },
      { value: 'SHE', label: 'Sheberghan' },
      { value: 'BAZ', label: 'Bamyan' },
      { value: 'PAN', label: 'Panjshir' },
      { value: 'JAW', label: 'Jowzjan' },
    ],
  
    // Albania
    AL: [
      { value: 'TIR', label: 'Tirana' },
      { value: 'SHK', label: 'Shkodra' },
      { value: 'DUR', label: 'Durrës' },
      { value: 'VLA', label: 'Vlorë' },
      { value: 'FIER', label: 'Fier' },
      { value: 'KUK', label: 'Kukës' },
      { value: 'BER', label: 'Berat' },
      { value: 'ELB', label: 'Elbasan' },
      { value: 'GJI', label: 'Gjirokastër' },
      { value: 'SAR', label: 'Saranda' },
      { value: 'LAZ', label: 'Lazare' },
      { value: 'DRR', label: 'Dropulli' },
      { value: 'SHK', label: 'Shkëmbi' },
      { value: 'PRA', label: 'Prang' },
      { value: 'SAR', label: 'Sharra' },
      { value: 'FUS', label: 'Fushe' },
      { value: 'LEZ', label: 'Lezhe' },
      { value: 'VRA', label: 'Vranishte' },
      { value: 'BIO', label: 'Bioleto' },
      { value: 'KRU', label: 'Krujë' },
    ],
  
    // Argelia
    DZ: [
      { value: 'ALGI', label: 'Argel' },
      { value: 'ORAN', label: 'Orán' },
      { value: 'CON', label: 'Constantina' },
      { value: 'SET', label: 'Setif' },
      { value: 'TLE', label: 'Tlemcen' },
      { value: 'FOU', label: 'Foucauld' },
      { value: 'BAH', label: 'Bahrain' },
      { value: 'TIZ', label: 'Tizi Ouzou' },
      { value: 'MED', label: 'Medea' },
      { value: 'KHOR', label: 'Khorasan' },
      { value: 'SOUK', label: 'Souk Ahras' },
      { value: 'NAIM', label: 'Naïma' },
      { value: 'GHAZ', label: 'Ghardaïa' },
      { value: 'BISK', label: 'Biskra' },
      { value: 'WAD', label: 'Ouargla' },
      { value: 'HASS', label: 'Hassiniyah' },
      { value: 'OID', label: 'Oued Rhiou' },
      { value: 'KHIR', label: 'Khirate' },
      { value: 'MEL', label: 'Meliana' },
      { value: 'MEL', label: 'Mellal' },
    ],
  
    // Andorra
    AD: [
      { value: 'AND', label: 'Andorra la Vella' },
      { value: 'ESC', label: 'Escaldes-Engordany' },
      { value: 'ENC', label: 'Encamp' },
      { value: 'LA MOS', label: 'La Massana' },
      { value: 'ORD', label: 'Ordino' },
      { value: 'SANT', label: 'Sant Julià de Lòria' },
      { value: 'SANT', label: 'Sant Andreu' },
      { value: 'SIT', label: 'Sitges' },
      { value: 'LA MAR', label: 'La Massana' },
      { value: 'COM', label: 'Comú' },
      { value: 'PRAT', label: 'Prats' },
      { value: 'SALS', label: 'Salt' },
      { value: 'BANY', label: 'Banyuls' },
      { value: 'SOL', label: 'Solsona' },
      { value: 'ALBER', label: 'Alberca' },
      { value: 'GRA', label: 'Grado' },
      { value: 'BEINS', label: 'Beinsa' },
      { value: 'MUN', label: 'Muncielles' },
      { value: 'PALS', label: 'Palau' },
      { value: 'LIR', label: 'Liérn' },
    ],
  
    // Angola
    AO: [
      { value: 'LUA', label: 'Luanda' },
      { value: 'HUI', label: 'Huíla' },
      { value: 'BIE', label: 'Bié' },
      { value: 'CUN', label: 'Cuanza Norte' },
      { value: 'CUN', label: 'Cuanza Sul' },
      { value: 'HUI', label: 'Huambo' },
      { value: 'MAL', label: 'Malanje' },
      { value: 'NAM', label: 'Namibe' },
      { value: 'ZAI', label: 'Zaire' },
      { value: 'CAB', label: 'Cabinda' },
      { value: 'BENG', label: 'Bengo' },
      { value: 'KUV', label: 'Kuando Kubango' },
      { value: 'KWZ', label: 'Kwanza Sul' },
      { value: 'KAHI', label: 'Kahenge' },
      { value: 'MAL', label: 'Malanje' },
      { value: 'LUDE', label: 'Lundas' },
      { value: 'ZAI', label: 'Zaire' },
      { value: 'LWELS', label: 'Lwels' },
      { value: 'HARI', label: 'Haruang' },
      { value: 'KIRI', label: 'Kirei' },
      { value: 'SIH', label: 'Sihome' },
    ],
  
    // Antigua y Barbuda
    AG: [
      { value: 'STJ', label: 'Saint John\'s' },
      { value: 'ALL', label: 'All Saints' },
      { value: 'BAR', label: 'Barbuda' },
      { value: 'MARN', label: 'Marian' },
      { value: 'CATA', label: 'Catana' },
      { value: 'CATT', label: 'Catamaran' },
      { value: 'MARS', label: 'Marsh Harbour' },
      { value: 'NURA', label: 'Nurse' },
      { value: 'WAS', label: 'Wasaga Beach' },
      { value: 'SALT', label: 'Salt Island' },
      { value: 'NICK', label: 'Nickel' },
      { value: 'SAV', label: 'Savannah' },
      { value: 'BIR', label: 'Bird' },
      { value: 'CUB', label: 'Cuba Bay' },
      { value: 'ARC', label: 'Arc' },
      { value: 'PRO', label: 'Prohere' },
      { value: 'CAN', label: 'Canaries' },
      { value: 'WIN', label: 'Windsor' },
      { value: 'MAGE', label: 'Makena' },
      { value: 'SED', label: 'Southern Elysium' },
      { value: 'PAC', label: 'Pacifica' },
    ],
  
    // Argentina
    AR: [
      { value: 'BA', label: 'Buenos Aires' },
      { value: 'CBA', label: 'Córdoba' },
      { value: 'ROS', label: 'Rosario' },
      { value: 'MEND', label: 'Mendoza' },
      { value: 'SAL', label: 'Salta' },
      { value: 'LAPlata', label: 'La Plata' },
      { value: 'SANL', label: 'San Luis' },
      { value: 'TUC', label: 'Tucumán' },
      { value: 'SAN', label: 'Santa Fe' },
      { value: 'NEU', label: 'Neuquén' },
      { value: 'CHB', label: 'Chubut' },
      { value: 'RIN', label: 'Río Negro' },
      { value: 'WAT', label: 'Formosa' },
      { value: 'RIO', label: 'Río Cuarto' },
      { value: 'CATA', label: 'Catamarca' },
      { value: 'BIA', label: 'Bialan' },
      { value: 'VIE', label: 'Vicente López' },
      { value: 'SEU', label: 'Sierra de la Ventana' },
      { value: 'JAS', label: 'Jaserdhos' },
      { value: 'GUA', label: 'Guaminí' },
      { value: 'ROD', label: 'Rogero' },
    ],
  
    // Armenia
    AM: [
      { value: 'YER', label: 'Erevan' },
      { value: 'GEG', label: 'Gegharkunik' },
      { value: 'ARAR', label: 'Ararat' },
      { value: 'LORI', label: 'Lori' },
      { value: 'VAY', label: 'Vayots Dzor' },
      { value: 'TAV', label: 'Tavush' },
      { value: 'SHIR', label: 'Shirak' },
      { value: 'KOT', label: 'Kotayk' },
      { value: 'SYU', label: 'Syunik' },
      { value: 'EGHE', label: 'Eghegnadzor' },
      { value: 'ARAR', label: 'Ararat' },
      { value: 'HRA', label: 'Hrazdan' },
      { value: 'ASHT', label: 'Ashtarak' },
      { value: 'VAG', label: 'Vagharshapat' },
      { value: 'AHKT', label: 'Akhuryan' },
      { value: 'ARTSH', label: 'Artashat' },
      { value: 'TAV', label: 'Tavush' },
      { value: 'NOVA', label: 'Novoye' },
      { value: 'KETS', label: 'Ketzalay' },
      { value: 'KAP', label: 'Kapan' },
    ],
  
    // Australia
    AU: [
      { value: 'NSW', label: 'Nueva Gales del Sur' },
      { value: 'VIC', label: 'Victoria' },
      { value: 'QLD', label: 'Queensland' },
      { value: 'WA', label: 'Australia Occidental' },
      { value: 'SA', label: 'Australia del Sur' },
      { value: 'TAS', label: 'Tasmania' },
      { value: 'ACT', label: 'Territorio de la Capital Australiana' },
      { value: 'NT', label: 'Territorio del Norte' },
      { value: 'GOLD', label: 'Gold Coast' },
      { value: 'SUN', label: 'Sunshine Coast' },
      { value: 'HOB', label: 'Hobart' },
      { value: 'CHA', label: 'Chadstone' },
      { value: 'BIR', label: 'Birminghame' },
      { value: 'SYD', label: 'Sídney' },
      { value: 'MEL', label: 'Melbourne' },
      { value: 'PER', label: 'Perth' },
      { value: 'CAN', label: 'Canberra' },
      { value: 'BRIS', label: 'Brisbane' },
      { value: 'ADE', label: 'Adelaida' },
      { value: 'HOB', label: 'Hobart' },
      { value: 'BUNN', label: 'Bunnings' },
    ],
  
    // Austria
    AT: [
      { value: 'VIE', label: 'Viena' },
      { value: 'GRA', label: 'Graz' },
      { value: 'LIN', label: 'Linz' },
      { value: 'SAL', label: 'Salzburgo' },
      { value: 'INN', label: 'Innsbruck' },
      { value: 'KLAG', label: 'Klagenfurt' },
      { value: 'STPO', label: 'St. Pölten' },
      { value: 'BREG', label: 'Bregenz' },
      { value: 'ROTT', label: 'Rottweil' },
      { value: 'NEUS', label: 'Neusiedl am See' },
      { value: 'WIE', label: 'Viena Nueva' },
      { value: 'HALL', label: 'Hall en Tierras' },
      { value: 'WELS', label: 'Wels' },
      { value: 'VILL', label: 'Villach' },
      { value: 'MIST', label: 'Mistelbach' },
      { value: 'SPIT', label: 'Spittal an der Drau' },
      { value: 'VIV', label: 'Vöcklabruck' },
      { value: 'AMST', label: 'Amstetten' },
      { value: 'STY', label: 'Steyr' },
      { value: 'BKN', label: 'Bruck an der Mur' },
    ],
  
    // Azerbaiyán
    AZ: [
      { value: 'BAK', label: 'Bakú' },
      { value: 'GAND', label: 'Ganja' },
      { value: 'LANK', label: 'Lankaran' },
      { value: 'SHIR', label: 'Shirvan' },
      { value: 'YARD', label: 'Yardimli' },
      { value: 'LOUD', label: 'Loudaj' },
      { value: 'GAB', label: 'Gabala' },
      { value: 'GHAN', label: 'Ganja' },
      { value: 'MIL', label: 'Milek' },
      { value: 'RIS', label: 'Risante' },
      { value: 'FIZ', label: 'Fizuli' },
      { value: 'ARDE', label: 'Ardebil' },
      { value: 'KORT', label: 'Kourty' },
      { value: 'KURDA', label: 'Kurda' },
      { value: 'KAC', label: 'Kachmaz' },
      { value: 'KHUL', label: 'Khulbuz' },
      { value: 'BAST', label: 'Bastak' },
      { value: 'BIL', label: 'Bilasuvar' },
      { value: 'NURD', label: 'Nukha' },
      { value: 'SHUS', label: 'Shushah' },
      { value: 'BILI', label: 'Bilasi' },
    ],
  
    // Las Bahamas
    BS: [
      { value: 'NAS', label: 'Nassau' },
      { value: 'GRAN', label: 'Grand Bahama' },
      { value: 'BAHI', label: 'Bimini' },
      { value: 'ABAC', label: 'Abaco' },
      { value: 'EXUM', label: 'Exuma' },
      { value: 'AND', label: 'Andros' },
      { value: 'LONG', label: 'Long Island' },
      { value: 'FAQA', label: 'Fort Charlotte' },
      { value: 'ELEU', label: 'Eleuthera' },
      { value: 'CRO', label: 'Crooked Island' },
      { value: 'AFOU', label: 'Afoos' },
      { value: 'BING', label: 'Bingua' },
      { value: 'CONH', label: 'Conhashat' },
      { value: 'MCHO', label: 'Mocho' },
      { value: 'KITT', label: 'Kittiwake' },
      { value: 'NARZ', label: 'Narcsal' },
      { value: 'NOR', label: 'North' },
      { value: 'SOU', label: 'South' },
      { value: 'VILI', label: 'Villanueva' },
      { value: 'GUS', label: 'Gustavus' },
    ],
  
    // Baréin
    BH: [
      { value: 'MAN', label: 'Manama' },
      { value: 'MUSH', label: 'Mushrif' },
      { value: 'NORTH', label: 'Gobernación del Norte' },
      { value: 'MUH', label: 'Muharraq' },
      { value: 'SIT', label: 'Sitra' },
      { value: 'HIDD', label: 'Hidd' },
      { value: 'JIDD', label: 'Jidd Hafs' },
      { value: 'NAD', label: 'Nad Al Hamar' },
      { value: 'N BRA', label: 'Bahréin Norte' },
      { value: 'ABU', label: 'Abu Samrah' },
      { value: 'AL ALI', label: 'Ali Al Shab' },
      { value: 'JAFNI', label: 'Jafni' },
      { value: 'MUHR', label: 'Muhras' },
      { value: 'TAM', label: 'Tamra' },
      { value: 'SEY', label: 'Sehle' },
      { value: 'HURA', label: 'Hurair' },
      { value: 'JAL', label: 'Jamal' },
      { value: 'SIN', label: 'Sin' },
      { value: 'RAC', label: 'Rac' },
      { value: 'MIS', label: 'Mezquita' },
    ],
  
    // Bangladés
    BD: [
      { value: 'DHA', label: 'Dhaka' },
      { value: 'CHIT', label: 'Chittagong' },
      { value: 'KHA', label: 'Khulna' },
      { value: 'RAJ', label: 'Rajshahi' },
      { value: 'BAR', label: 'Barisal' },
      { value: 'SYL', label: 'Sylhet' },
      { value: 'NAR', label: 'Narail' },
      { value: 'NARS', label: 'Narsingdi' },
      { value: 'SAV', label: 'Savighat' },
      { value: 'MAG', label: 'Magura' },
      { value: 'MUL', label: 'Moulvibazar' },
      { value: 'DINA', label: 'Dinajpur' },
      { value: 'JESS', label: 'Jessore' },
      { value: 'KOT', label: 'Koto' },
      { value: 'UJN', label: 'Ujanagar' },
      { value: 'COX', label: 'Cox\'s Bazar' },
      { value: 'BOH', label: 'Bohmanpara' },
      { value: 'BIR', label: 'Birsara' },
      { value: 'LIZ', label: 'Lizardi' },
      { value: 'KISM', label: 'Kismat' },
      { value: 'NESW', label: 'Nesward' },
    ],
  
    // Barbados
    BB: [
      { value: 'BRIS', label: 'Bridgetown' },
      { value: 'STMI', label: 'Saint Michael' },
      { value: 'STPH', label: 'Saint Philip' },
      { value: 'STGE', label: 'Saint George' },
      { value: 'STJO', label: 'Saint Joseph' },
      { value: 'STLU', label: 'Saint Lucy' },
      { value: 'STPA', label: 'Saint Patrick' },
      { value: 'STPE', label: 'Saint Peter' },
      { value: 'STTH', label: 'Saint Thomas' },
      { value: 'STJA', label: 'Saint James' },
      { value: 'STJO', label: 'Saint John' },
      { value: 'HOPE', label: 'Hope' },
      { value: 'DELF', label: 'Delft' },
      { value: 'LAIM', label: 'Laimwood' },
      { value: 'LUMI', label: 'Lumina' },
      { value: 'MIL', label: 'Millenium' },
      { value: 'DOL', label: 'Doylehill' },
      { value: 'PLOM', label: 'Plomond' },
      { value: 'ROSE', label: 'Rose Place' },
      { value: 'HANI', label: 'Hanis' },
      { value: 'GRA', label: 'Grand Bassin' },
    ],
  
    // Bielorrusia
    BY: [
      { value: 'MIN', label: 'Minsk' },
      { value: 'BRES', label: 'Brest' },
      { value: 'VITE', label: 'Vitebsk' },
      { value: 'GROD', label: 'Grodno' },
      { value: 'MOGI', label: 'Mogilev' },
      { value: 'GOML', label: 'Gomel' },
      { value: 'DRAH', label: 'Drahichyn' },
      { value: 'KOST', label: 'Kostyukovka' },
      { value: 'RAZ', label: 'Razdolye' },
      { value: 'SMO', label: 'Smorgon' },
      { value: 'SOL', label: 'Soligorsk' },
      { value: 'KLIC', label: 'Klicz' },
      { value: 'KALG', label: 'Kaluga' },
      { value: 'PORY', label: 'Porya' },
      { value: 'STAN', label: 'Stanislav' },
      { value: 'SIRE', label: 'Sireny' },
      { value: 'AKH', label: 'Takmut' },
      { value: 'TINK', label: 'Tinkov' },
      { value: 'GOR', label: 'Gorod' },
      { value: 'HANA', label: 'Hanna' },
      { value: 'YALI', label: 'Yalsi' },
    ],
  
    // Bélgica
    BE: [
      { value: 'BRU', label: 'Bruselas' },
      { value: 'ANTW', label: 'Antwerpen' },
      { value: 'FLA', label: 'Flandes' },
      { value: 'WALL', label: 'Valonia' },
      { value: 'BRAB', label: 'Brabante' },
      { value: 'NAMU', label: 'Namur' },
      { value: 'LIE', label: 'Liège' },
      { value: 'HEN', label: 'Hainaut' },
      { value: 'EAST', label: 'Flandes Oriental' },
      { value: 'WEST', label: 'Flandes Occidental' },
      { value: 'BRV', label: 'Bruselas-Capital' },
      { value: 'WALL', label: 'Brabante Valón' },
      { value: 'LUX', label: 'Luxemburgo' },
      { value: 'FLA', label: 'Brabante Flamenco' },
      { value: 'VLA', label: 'Vlaams-Brabant' },
      { value: 'TER', label: 'Terraigne' },
      { value: 'KOR', label: 'Kortez' },
      { value: 'ZON', label: 'Zoning' },
      { value: 'ZUI', label: 'Zuid' },
      { value: 'OOST', label: 'Oost-Vlaanderen' },
      { value: 'KAP', label: 'Kapellen' },
    ],
  
    // Belice
    BZ: [
      { value: 'BEL', label: 'Belmopan' },
      { value: 'CAY', label: 'Cayo' },
      { value: 'CORO', label: 'Corozal' },
      { value: 'ORAN', label: 'Orange Walk' },
      { value: 'SAN', label: 'San Pedro' },
      { value: 'STAN', label: 'Stann Creek' },
      { value: 'TOLE', label: 'Toledo' },
      { value: 'BACO', label: 'Bacom' },
      { value: 'GERS', label: 'Gershcourse' },
      { value: 'HOP', label: 'Hopkins' },
      { value: 'FLAM', label: 'Flamingo' },
      { value: 'GREG', label: 'Gregory' },
      { value: 'NEV', label: 'Neville' },
      { value: 'SAIL', label: 'Sailley' },
      { value: 'MORN', label: 'Morningstar' },
      { value: 'OVEN', label: 'Overhill' },
      { value: 'VAL', label: 'Valley' },
      { value: 'CABL', label: 'Cabli' },
      { value: 'CRO', label: 'Crocus' },
      { value: 'ROSI', label: 'Rosental' },
      { value: 'SANTA', label: 'Santa Elena' },
    ],
  
    // Benín
    BJ: [
      { value: 'COT', label: 'Cotonou' },
      { value: 'PAR', label: 'Parakou' },
      { value: 'KOU', label: 'Kouffo' },
      { value: 'NAT', label: 'Natin' },
      { value: 'DONG', label: 'Dongari' },
      { value: 'ALAR', label: 'Alibori' },
      { value: 'ALL', label: 'Allada' },
      { value: 'AV', label: 'Avenue' },
      { value: 'DONG', label: 'Dongari' },
      { value: 'GAZI', label: 'Gazgoulin' },
      { value: 'KOUND', label: 'Kounda' },
      { value: 'OUM', label: 'Oumou' },
      { value: 'INFO', label: 'Infossin' },
      { value: 'KIS', label: 'Kissagou' },
      { value: 'KET', label: 'Ketou' },
      { value: 'PEHA', label: 'Peha' },
      { value: 'DRA', label: 'Dra' },
      { value: 'BESS', label: 'Benassi' },
      { value: 'MOD', label: 'Modjari' },
      { value: 'BEC', label: 'Becalet' },
      { value: 'SEK', label: 'Seme-Kranklin' },
    ],
  
    // Bután
    BT: [
      { value: 'THI', label: 'Thimphu' },
      { value: 'PUN', label: 'Punakha' },
      { value: 'BUM', label: 'Bumthang' },
      { value: 'GASA', label: 'Gasa' },
      { value: 'PRA', label: 'Paro' },
      { value: 'KHA', label: 'Khadras' },
      { value: 'LAM', label: 'Lhamoizingkha' },
      { value: 'URUL', label: 'Ura' },
      { value: 'NAR', label: 'Naru' },
      { value: 'JAL', label: 'Jaldapara' },
      { value: 'GIEL', label: 'Gielit' },
      { value: 'PUMPA', label: 'Pumpha' },
      { value: 'HRA', label: 'Marakha' },
      { value: 'LHA', label: 'Lha' },
      { value: 'BRAIN', label: 'Brain' },
      { value: 'ROP', label: 'Rop' },
      { value: 'LORE', label: 'Lore' },
      { value: 'KAN', label: 'Kanjpur' },
      { value: 'DRAK', label: 'Draksh' },
      { value: 'KINK', label: 'Kinkim' },
      { value: 'NARO', label: 'Narong' },
    ],
  
    // Bolivia
    BO: [
      { value: 'LPZ', label: 'La Paz' },
      { value: 'CBA', label: 'Cochabamba' },
      { value: 'CBA', label: 'Santa Cruz' },
      { value: 'TAR', label: 'Tarija' },
      { value: 'POT', label: 'Potosí' },
      { value: 'SUC', label: 'Sucre' },
      { value: 'BENC', label: 'Beni' },
      { value: 'PANDO', label: 'Pando' },
      { value: 'ARES', label: 'Ares' },
      { value: 'TIR', label: 'Tierra' },
      { value: 'CHAP', label: 'Chaptal' },
      { value: 'CHI', label: 'Chilpa' },
      { value: 'VILL', label: 'Villar' },
      { value: 'INKA', label: 'Incache' },
      { value: 'MAV', label: 'Maviro' },
      { value: 'TANG', label: 'Tangamire' },
      { value: 'NINO', label: 'Ninos' },
      { value: 'PIO', label: 'Piotros' },
      { value: 'SUVA', label: 'Suav' },
      { value: 'RIVA', label: 'Rivah' },
      { value: 'PUMAPEA', label: 'Pumapea' },
    ],
  
    // Bosnia y Herzegovina
    BA: [
      { value: 'SARA', label: 'Sarajevo' },
      { value: 'BANA', label: 'Banovići' },
      { value: 'DOBO', label: 'Doboj' },
      { value: 'BIHA', label: 'Bihać' },
      { value: 'GOR', label: 'Goražde' },
      { value: 'ZENI', label: 'Zenica' },
      { value: 'BOR', label: 'Bora' },
      { value: 'MRO', label: 'Mratin' },
      { value: 'FUJA', label: 'Fujambo' },
      { value: 'SKNER', label: 'Skender' },
      { value: 'RIB', label: 'Ribnik' },
      { value: 'LAV', label: 'Lavville' },
      { value: 'PALE', label: 'Pale' },
      { value: 'CERC', label: 'Cercula' },
      { value: 'VOSE', label: 'Vose' },
      { value: 'DRINA', label: 'Drina' },
      { value: 'CURA', label: 'Curac' },
      { value: 'KAZ', label: 'Kazandol' },
      { value: 'KRS', label: 'Krsa' },
      { value: 'BALE', label: 'Balenja' },
      { value: 'LAAV', label: 'Laavan' },
    ],
  
    // Botsuana
    BW: [
      { value: 'GAB', label: 'Gaborone' },
      { value: 'MAH', label: 'Mahalapye' },
      { value: 'KWEN', label: 'Kweneng' },
      { value: 'NAMA', label: 'Ngami' },
      { value: 'SVEN', label: 'Southeast' },
      { value: 'SERE', label: 'Serowe' },
      { value: 'MOLA', label: 'Molepolole' },
      { value: 'VILL', label: 'Villiers' },
      { value: 'HOPE', label: 'Hope' },
      { value: 'TULI', label: 'Tuli' },
      { value: 'PAL', label: 'Palapye' },
      { value: 'ROL', label: 'Rolupe' },
      { value: 'MAQU', label: 'Maqueto' },
      { value: 'MAPPY', label: 'Mafikeng' },
      { value: 'MOTI', label: 'Motlhabe' },
      { value: 'KIM', label: 'Kiman' },
      { value: 'KAT', label: 'Katana' },
      { value: 'ASH', label: 'Ashdoing' },
      { value: 'ATT', label: 'Attata' },
      { value: 'PGOMA', label: 'Mmaba' },
      { value: 'BUCK', label: 'Buckingham' },
    ],
  
    // Brasil
    BR: [
      { value: 'SAO', label: 'São Paulo' },
      { value: 'RJO', label: 'Río de Janeiro' },
      { value: 'BAH', label: 'Bahia' },
      { value: 'CBA', label: 'Ceará' },
      { value: 'GRU', label: 'Grubet Dubassu' },
      { value: 'EC', label: 'Eclan' },
      { value: 'MIN', label: 'Minas Gerais' },
      { value: 'PAR', label: 'Pará' },
      { value: 'MS', label: 'Mato Grosso do Sul' },
      { value: 'MATO', label: 'Mato Grosso' },
      { value: 'GRO', label: 'Goiás' },
      { value: 'PERN', label: 'Pernambuco' },
      { value: 'RIE', label: 'Rio Grande do Sul' },
      { value: 'DURE', label: 'Durando' },
      { value: 'MESA', label: 'Sherando' },
      { value: 'IMB', label: 'Serra' },
      { value: 'JUR', label: 'Journey' },
      { value: 'GUARA', label: 'Guaratingual' },
      { value: 'SOR', label: 'Sorocaba' },
      { value: 'VILA', label: 'Vila Velha' },
      { value: 'GRU', label: 'Guarujá' },
    ],
  
    // Brunéi
    BN: [
      { value: 'BANDAR', label: 'Bandar Seri Begawan' },
      { value: 'BELAIT', label: 'Belait' },
      { value: 'TUTONG', label: 'Tutong' },
      { value: 'TEMBURONG', label: 'Temburong' },
      { value: 'LUTONG', label: 'Lutong' },
      { value: 'KUALA', label: 'Kuala Belait' },
      { value: 'MUMIN', label: 'Mumin' },
      { value: 'KERSIK', label: 'Kersik Gawai' },
      { value: 'AMPANG', label: 'Ampang' },
      { value: 'GILBAN', label: 'Gilban South' },
      { value: 'BANG', label: 'Bangar' },
      { value: 'TANJUNG', label: 'Tanjung' },
      { value: 'RUBER', label: 'Ruber' },
      { value: 'LAMAR', label: 'Lamar' },
      { value: 'SELEK', label: 'Selekong' },
      { value: 'BOKER', label: 'Boker' },
      { value: 'PARING', label: 'Paring' },
      { value: 'BANTAY', label: 'Bantay' },
      { value: 'NANAS', label: 'Nanas' },
      { value: 'SUNGAI', label: 'Sungai Kebun' },
      { value: 'SERI', label: 'Serasa' },
    ],
  
    // Bulgaria
    BG: [
      { value: 'SOF', label: 'Sofía' },
      { value: 'PLV', label: 'Plovdiv' },
      { value: 'VAR', label: 'Varna' },
      { value: 'BUR', label: 'Burgas' },
      { value: 'RUS', label: 'Ruse' },
      { value: 'STARA', label: 'Stara Zagora' },
      { value: 'KAZ', label: 'Kazansk' },
      { value: 'BLA', label: 'Blagoevgrad' },
      { value: 'PERN', label: 'Pernik' },
      { value: 'VRA', label: 'Vratsa' },
      { value: 'LOVE', label: 'Lovech' },
      { value: 'SIL', label: 'Silistra' },
      { value: 'GAB', label: 'Gabrovo' },
      { value: 'YAM', label: 'Yambol' },
      { value: 'SAND', label: 'Sandanski' },
      { value: 'MADA', label: 'Madara' },
      { value: 'DEST', label: 'Destan' },
      { value: 'RUS', label: 'Ruse' },
      { value: 'LOL', label: 'Lolevit' },
      { value: 'PARD', label: 'Pardagrang' },
      { value: 'PATR', label: 'Patra' },
    ],
  
    // Burkina Faso
    BF: [
      { value: 'OUAG', label: 'Ouagadougou' },
      { value: 'BAM', label: 'Bamako' },
      { value: 'BOBO', label: 'Bobo-Dioulasso' },
      { value: 'KADO', label: 'Kadiogo' },
      { value: 'KOU', label: 'Koudougou' },
      { value: 'BAM', label: 'Banfora' },
      { value: 'NAHO', label: 'Naho' },
      { value: 'NENY', label: 'Neny' },
      { value: 'RAN', label: 'Ranchor' },
      { value: 'NOU', label: 'Noumbiel' },
      { value: 'GOUT', label: 'Gouta' },
      { value: 'NAINI', label: 'Naini' },
      { value: 'KOT', label: 'Kottum' },
      { value: 'GAL', label: 'Galmus' },
      { value: 'SOR', label: 'Sorrib' },
      { value: 'DAB', label: 'Dabo' },
      { value: 'WOUE', label: 'Woouin' },
      { value: 'AMBI', label: 'Ambikan' },
      { value: 'LAV', label: 'Lava' },
      { value: 'DODO', label: 'Dodoma' },
      { value: 'MAB', label: 'Maboun' },
    ],
  
    // Burundi
    BI: [
      { value: 'GITE', label: 'Gitega' },
      { value: 'BUJ', label: 'Bujumbura' },
      { value: 'MUY', label: 'Muyinga' },
      { value: 'KIR', label: 'Kirundo' },
      { value: 'RUT', label: 'Rutana' },
      { value: 'KAY', label: 'Kayanza' },
      { value: 'PAR', label: 'Parmi Masi' },
      { value: 'YAF', label: 'Yafre' },
      { value: 'BUJOR', label: 'Bujanbura' },
      { value: 'LIB', label: 'Libero' },
      { value: 'RUM', label: 'Ruying' },
      { value: 'MUR', label: 'Muramvya' },
      { value: 'NTA', label: 'Ntahangwa' },
      { value: 'NTAHU', label: 'Ntahangwa' },
      { value: 'GIS', label: 'Gishubi' },
      { value: 'MUYI', label: 'Muyinga' },
      { value: 'CGL', label: 'Cagagu' },
      { value: 'BUW', label: 'Burundi' },
      { value: 'RKA', label: 'Rukoko' },
      { value: 'MUS', label: 'Musaga' },
      { value: 'MWI', label: 'Mwira' },
    ],
  
    // Cabo Verde
    CV: [
      { value: 'PRA', label: 'Praia' },
      { value: 'SAO', label: 'São Vicente' },
      { value: 'SAL', label: 'Sal' },
      { value: 'SANTI', label: 'Santiago' },
      { value: 'BOA', label: 'Boa Vista' },
      { value: 'FOGO', label: 'Fogo' },
      { value: 'MAI', label: 'Maio' },
      { value: 'URLA', label: 'Urla' },
      { value: 'ODIB', label: 'Odih' },
      { value: 'SATA', label: 'Sata' },
      { value: 'QUIN', label: 'Quinbuz' },
      { value: 'QUE', label: 'Queimad' },
      { value: 'CHOY', label: 'Choydar' },
      { value: 'PAN', label: 'Panchilli' },
      { value: 'BOC', label: 'Bocarra' },
      { value: 'DURI', label: 'Durubuka' },
      { value: 'AGU', label: 'Agua Penta' },
      { value: 'FUG', label: 'Fugle' },
      { value: 'KOR', label: 'Korith' },
      { value: 'OLI', label: 'Olhaldo' },
    ],
  
    // Camboya
    KH: [
      { value: 'PHN', label: 'Phnom Penh' },
      { value: 'SIH', label: 'Siem Reap' },
      { value: 'BATT', label: 'Battambang' },
      { value: 'KAND', label: 'Kandal' },
      { value: 'TAKEO', label: 'Takeo' },
      { value: 'KAMP', label: 'Kampong Cham' },
      { value: 'KAMP', label: 'Kampong Speu' },
      { value: 'KAMPOT', label: 'Kampot' },
      { value: 'MOND', label: 'Mondulkiri' },
      { value: 'RAT', label: 'Ratanakiri' },
      { value: 'PREY', label: 'Prey Veng' },
      { value: 'SVAY', label: 'Svay Rieng' },
      { value: 'POUR', label: 'Pursat' },
      { value: 'KRA', label: 'Kraches' },
      { value: 'STUN', label: 'Stung Treng' },
      { value: 'MUND', label: 'Mundulkiri' },
      { value: 'BOK', label: 'Bokor' },
      { value: 'DOU', label: 'Doueng' },
      { value: 'MEANC', label: 'Meanchey' },
      { value: 'ROA', label: 'Roang' },
      { value: 'KAMP', label: 'Kampon' },
    ],
  
    // Camerún
    CM: [
      { value: 'YAOUN', label: 'Yaoundé' },
      { value: 'DOUAL', label: 'Douala' },
      { value: 'NGA', label: 'Ngaoundéré' },
      { value: 'BAM', label: 'Bamenda' },
      { value: 'BERT', label: 'Bertoua' },
      { value: 'EKOK', label: 'Ebolowa' },
      { value: 'KRIB', label: 'Kribi' },
      { value: 'BAT', label: 'Bafoussam' },
      { value: 'GAR', label: 'Garoua' },
      { value: 'MAR', label: 'Maroua' },
      { value: 'KOM', label: 'Kombo' },
      { value: 'CENT', label: 'Centro' },
      { value: 'LITT', label: 'Litoral' },
      { value: 'SUD', label: 'Sur' },
      { value: 'NORD', label: 'Norte' },
      { value: 'OUEST', label: 'Oeste' },
      { value: 'EST', label: 'Este' },
      { value: 'ADAM', label: 'Adamaoua' },
      { value: 'SOUT', label: 'Besogne' },
      { value: 'SF', label: 'Suroeste' },
      { value: 'ATH', label: 'Atenas' },
    ],
  
    // Canadá
    CA: [
      { value: 'ONT', label: 'Ontario' },
      { value: 'QUE', label: 'Quebec' },
      { value: 'BC', label: 'Columbia Británica' },
      { value: 'ALB', label: 'Alberta' },
      { value: 'MAN', label: 'Manitoba' },
      { value: 'SASK', label: 'Saskatchewan' },
      { value: 'NS', label: 'Nueva Escocia' },
      { value: 'NBL', label: 'Nuevo Brunswick' },
      { value: 'NFL', label: 'Terranova y Labrador' },
      { value: 'PRIN', label: 'Isla del Príncipe Eduardo' },
      { value: 'YT', label: 'Yukón' },
      { value: 'NWT', label: 'Territorios del Noroeste' },
      { value: 'NU', label: 'Nunavut' },
      { value: 'OTW', label: 'Quebec Exterior' },
      { value: 'EDM', label: 'Edmonton' },
      { value: 'HAL', label: 'Halifax' },
      { value: 'CHUR', label: 'Chur' },
      { value: 'ABOT', label: 'Abbotsford' },
      { value: 'VAN', label: 'Vancouver' },
      { value: 'TOR', label: 'Toronto' },
    ],
  
    // República Centroafricana
    CF: [
      { value: 'BANG', label: 'Bangui' },
      { value: 'BAM', label: 'Bamingui-Bangoran' },
      { value: 'OUMB', label: 'Ombella-Mpoko' },
      { value: 'SANG', label: 'Sangha-Mbaéré' },
      { value: 'MBOM', label: 'Mbomou' },
      { value: 'WAM', label: 'Wam' },
      { value: 'NANA', label: 'Nana-Bakassa' },
      { value: 'HOM', label: 'Hommage' },
      { value: 'MOB', label: 'Mobaye' },
      { value: 'LANA', label: 'Langu' },
      { value: 'BOSS', label: 'Bossangoa' },
      { value: 'GRAND', label: 'Gran Mbella' },
      { value: 'OIRA', label: 'Oira' },
      { value: 'NDA', label: 'Nda-Aname' },
      { value: 'GAA', label: 'Gaaba' },
      { value: 'KET', label: 'Ket' },
      { value: 'YAND', label: 'Yand' },
      { value: 'KIA', label: 'Kia' },
      { value: 'NAMB', label: 'Nambion' },
      { value: 'KIT', label: 'Kita' },
    ],
  
    // Chile
    CL: [
      { value: 'SANTI', label: 'Santiago' },
      { value: 'VAL', label: 'Valparaíso' },
      { value: 'ANTO', label: 'Antofagasta' },
      { value: 'BIOD', label: 'Bío Bío' },
      { value: 'LAAR', label: 'Láser' },
      { value: 'ARICA', label: 'Arica y Parinacota' },
      { value: 'MUL', label: 'Maule' },
      { value: 'TAK', label: 'Takahashi' },
      { value: 'LESF', label: 'Les Fleurs' },
      { value: 'PAMA', label: 'Pampa' },
      { value: 'NAN', label: 'Nanquim' },
      { value: 'HUAUNC', label: 'Huanque' },
      { value: 'VAL', label: 'Viña del Mar' },
      { value: 'COL', label: 'Colin' },
      { value: 'DOA', label: 'Dona' },
      { value: 'TRIAN', label: 'Triana' },
      { value: 'FUND', label: 'Fundar' },
      { value: 'POLO', label: 'Polonia' },
      { value: 'MATE', label: 'Mate' },
      { value: 'ARAC', label: 'Aracor' },
      { value: 'DURA', label: 'Durafri' },
    ],
  
    // China
    CN: [
      { value: 'BJ', label: 'Pekín' },
      { value: 'SH', label: 'Shanghái' },
      { value: 'GZ', label: 'Guangzhou' },
      { value: 'SZ', label: 'Shenzhen' },
      { value: 'WUH', label: 'Wuhan' },
      { value: 'SUZ', label: 'Suzhou' },
      { value: 'NANJ', label: 'Nanjing' },
      { value: 'CHG', label: 'Changsha' },
      { value: 'WAN', label: 'Wanzhou' },
      { value: 'XIAM', label: 'Xiamen' },
      { value: 'NING', label: 'Ningbo' },
      { value: 'HANG', label: 'Hangzhou' },
      { value: 'MANG', label: 'Mangu' },
      { value: 'LUOY', label: 'Luoyang' },
      { value: 'JIA', label: 'Jiangxi' },
      { value: 'HEN', label: 'Henan' },
      { value: 'BEI', label: 'Pekín' },
      { value: 'ZHE', label: 'Zhejiang' },
      { value: 'HEB', label: 'Hebei' },
      { value: 'QIN', label: 'Qinghai' },
      { value: 'YN', label: 'Yunnan' },
    ],
  
    // Colombia
    CO: [
      { value: 'BOG', label: 'Bogotá' },
      { value: 'MED', label: 'Medellín' },
      { value: 'CALI', label: 'Cali' },
      { value: 'BARR', label: 'Barranquilla' },
      { value: 'CART', label: 'Cartagena' },
      { value: 'BUC', label: 'Bucaramanga' },
      { value: 'SOCA', label: 'Socorro' },
      { value: 'TUNJ', label: 'Tunja' },
      { value: 'CÚC', label: 'Cúcuta' },
      { value: 'PIE', label: 'Piedecuesta' },
      { value: 'MAGA', label: 'Magangué' },
      { value: 'PAST', label: 'Pasto' },
      { value: 'MANI', label: 'Manizales' },
      { value: 'LAF', label: 'La Florida' },
      { value: 'MANA', label: 'Magdalena' },
      { value: 'NEIVA', label: 'Neiva' },
      { value: 'MOY', label: 'Moyobamba' },
      { value: 'SANT', label: 'San Juan' },
      { value: 'ANGE', label: 'Angelopolis' },
      { value: 'TOLI', label: 'Tolima' },
      { value: 'SUCH', label: 'Suchitoto' },
    ],
  
    // Comoras
    KM: [
      { value: 'MOR', label: 'Moroni' },
      { value: 'MHO', label: 'Mitsamiouli' },
      { value: 'MOZ', label: 'Mozambique' },
      { value: 'NYE', label: 'Nyanga' },
      { value: 'MKW', label: 'Mokavage' },
      { value: 'SULT', label: 'Sultana' },
      { value: 'LAL', label: 'Lalaha' },
      { value: 'BAB', label: 'Babou' },
      { value: 'KJO', label: 'Kajo' },
      { value: 'OYE', label: 'Oye' },
      { value: 'SWE', label: 'Sawa' },
      { value: 'NEHE', label: 'Nehaba' },
      { value: 'GAS', label: 'Gasparweda' },
      { value: 'GLI', label: 'Glia' },
      { value: 'NGW', label: 'Nganja' },
      { value: 'MBEG', label: 'Mbegathem' },
      { value: 'GANT', label: 'Gantou' },
      { value: 'FAT', label: 'Fatima' },
      { value: 'SON', label: 'Sonebatia' },
      { value: 'SAMB', label: 'Sambuludu' },
      { value: 'MERS', label: 'Mersar' },
    ],
  
    // Congo
    CG: [
      { value: 'BRA', label: 'Brazzaville' },
      { value: 'POIN', label: 'Point Noire' },
      { value: 'LUCRA', label: 'Luanda' },
      { value: 'SANG', label: 'Sangha' },
      { value: 'OUAN', label: 'Ouan' },
      { value: 'MPOKO', label: 'Mpoke' },
      { value: 'NIK', label: 'Mikongo' },
      { value: 'LIK', label: 'Likouala' },
      { value: 'MOUA', label: 'Mouanda' },
      { value: 'NIAM', label: 'Niamboko' },
      { value: 'MALABO', label: 'Malabo' },
      { value: 'SWA', label: 'Swami' },
      { value: 'BONG', label: 'Bongolo' },
      { value: 'NAB', label: 'Nabou' },
      { value: 'FJO', label: 'Fjoq' },
      { value: 'TAN', label: 'Tanji' },
      { value: 'NOK', label: 'Nombela' },
      { value: 'REK', label: 'Rekoto' },
      { value: 'ZUI', label: 'Zuil' },
      { value: 'BITE', label: 'Bite' },
      { value: 'AVAN', label: 'Avandy' },
    ],
  
    // República Democrática del Congo
    CD: [
      { value: 'KIN', label: 'Kinshasa' },
      { value: 'LUB', label: 'Lubumbashi' },
      { value: 'GN', label: 'Goma' },
      { value: 'MBAN', label: 'Mbandaka' },
      { value: 'KASA', label: 'Kasaï' },
      { value: 'KATA', label: 'Katanga' },
      { value: 'NORD', label: 'Nord-Kivu' },
      { value: 'SUD', label: 'Sud-Kivu' },
      { value: 'TSH', label: 'Tshuapa' },
      { value: 'TSHO', label: 'Tshopo' },
      { value: 'HOO', label: 'Haut-Lomami' },
      { value: 'SUNK', label: 'Sunkuru' },
      { value: 'MAN', label: 'Maniema' },
      { value: 'LUAL', label: 'Lualaba' },
      { value: 'KISAN', label: 'Kisangani' },
      { value: 'BAND', label: 'Bandundu' },
      { value: 'BAS', label: 'Bas-Congo' },
      { value: 'Haut-Mayumbe', label: 'Haut-Katanga' },
      { value: 'MAC', label: 'Makaya' },
      { value: 'MON', label: 'Monas' },
      { value: 'NYA', label: 'Nyanga' },
    ],
  
    // Dinamarca
    DK: [
      { value: 'CPH', label: 'Copenhague' },
      { value: 'AAL', label: 'Aalborg' },
      { value: 'ARH', label: 'Aarhus' },
      { value: 'ODD', label: 'Odense' },
      { value: 'VIB', label: 'Viborg' },
      { value: 'DIG', label: 'Digin' },
      { value: 'FLA', label: 'Flaaberg' },
      { value: 'OSE', label: 'Ose' },
      { value: 'MAR', label: 'Maribo' },
      { value: 'NAA', label: 'Nadler' },
      { value: 'MID', label: 'Middelfart' },
      { value: 'LUN', label: 'Lund' },
      { value: 'HÅL', label: 'Hål' },
      { value: 'RYA', label: 'Ry' },
      { value: 'KIR', label: 'Kirkenes' },
      { value: 'MAR', label: 'Marfor' },
      { value: 'CLY', label: 'Clarkston' },
      { value: 'AVE', label: 'Aveland' },
      { value: 'LEJ', label: 'Lejid' },
      { value: 'TOR', label: 'Torped' },
      { value: 'LAN', label: 'Lande' },
    ],
  
    // Dominica
    DM: [
      { value: 'ROSE', label: 'Roseau' },
      { value: 'PORT', label: 'Portsmouth' },
      { value: 'MAR', label: 'Marigot' },
      { value: 'ROSE', label: 'Riverside' },
      { value: 'MARRI', label: 'Marrike' },
      { value: 'PORT', label: 'Portsmouth' },
      { value: 'MERO', label: 'Mero' },
      { value: 'SOUT', label: 'South' },
      { value: 'REST', label: 'Reserve' },
      { value: 'SUMP', label: 'Sumpter' },
      { value: 'ROSE', label: 'Roosevelt' },
      { value: 'SAMP', label: 'Sampford' },
      { value: 'SEA', label: 'Seaward' },
      { value: 'ROSE', label: 'Rosewood' },
      { value: 'LAN', label: 'Lanf' },
      { value: 'MAN', label: 'Mansion' },
      { value: 'VISTA', label: 'Vista' },
      { value: 'SGONE', label: 'Sigone' },
      { value: 'ROV', label: 'Rovent' },
      { value: 'RECA', label: 'Recaltong' },
      { value: 'CRAE', label: 'Craeton' },
    ],
  
    // República Dominicana
    DO: [
      { value: 'SANTO', label: 'Santo Domingo' },
      { value: 'SANTI', label: 'Santiago' },
      { value: 'SANTI', label: 'San Cristóbal' },
      { value: 'DUGE', label: 'Dajabón' },
      { value: 'EL-G', label: 'El Gran ' },
      { value: 'Nortes', label: 'Norte' },
      { value: 'TEOR', label: 'Teorald' },
      { value: 'MAN', label: 'Mansa' },
      { value: 'BAY', label: 'Bayaguano' },
      { value: 'LA ROM', label: 'La Romana' },
      { value: 'BAIE', label: 'Baie de Henne' },
      { value: 'HIGH', label: 'High' },
      { value: 'CHAR', label: 'Charok' },
      { value: 'MARE', label: 'Maresir' },
      { value: 'FONN', label: 'Fonnal' },
      { value: 'SLAN', label: 'Slang' },
      { value: 'AIR', label: 'Airi' },
      { value: 'GRAN', label: 'Gran' },
      { value: 'GER', label: 'Gerio' },
      { value: 'AUM', label: 'Aumin' },
      { value: 'CHEZ', label: 'Chezig' },
    ],
  
    // Ecuador
    EC: [
      { value: 'QUI', label: 'Quito' },
      { value: 'GUAY', label: 'Guayaquil' },
      { value: 'CUEN', label: 'Cuenca' },
      { value: 'MACH', label: 'Machala' },
      { value: 'LORE', label: 'Loreto' },
      { value: 'SUCU', label: 'Sucumbíos' },
      { value: 'PICH', label: 'Pichincha' },
      { value: 'AZU', label: 'Azuay' },
      { value: 'TUNG', label: 'Tungurahua' },
      { value: 'BRIT', label: 'Brickel' },
      { value: 'BIANCH', label: 'Bianchata' },
      { value: 'LORE', label: 'Loreto' },
      { value: 'MIER', label: 'Mina Lacka' },
      { value: 'CHIM', label: 'Chimborazo' },
      { value: 'HUAQU' , label: 'Huaquillas' },
      { value: 'AUQUI', label: 'Aukri' },
      { value: 'VILL', label: 'Villanueva' },
      { value: 'MIRA', label: 'Miranda' },
      { value: 'SAMB', label: 'Samborondon' },
      { value: 'RIS', label: 'Rizal' },
      { value: 'ZAMB', label: 'Zambaldocus' },
    ],
  
    // Egipto
    EG: [
      { value: 'CAI', label: 'El Cairo' },
      { value: 'GHA', label: 'Giza' },
      { value: 'QAL', label: 'Qalyubia' },
      { value: 'DAK', label: 'Dakahlia' },
      { value: 'SHR', label: 'Sharkia' },
      { value: 'KHE', label: 'Khedivate Tel Mahrusa' },
      { value: 'ASU', label: 'Asuán' },
      { value: 'ALX', label: 'Alejandría' },
      { value: 'MIN', label: 'Minya' },
      { value: 'FAY', label: 'Fayoum' },
      { value: 'MAT', label: 'Matruh' },
      { value: 'NWE', label: 'New Valley' },
      { value: 'MERS', label: 'Mersa Matruh' },
      { value: 'ISN', label: 'Ismailia' },
      { value: 'BEC', label: 'Behera' },
      { value: 'QENA', label: 'Qena' },
      { value: 'SUH', label: 'Suhaj' },
      { value: 'ASU', label: 'Asyut' },
      { value: 'BANY', label: 'Beni Suef' },
      { value: 'PORT', label: 'Puerto Saíd' },
    ],
  
    // El Salvador
    SV: [
      { value: 'SAN', label: 'San Salvador' },
      { value: 'SON', label: 'Sonsonate' },
      { value: 'LA', label: 'La Libertad' },
      { value: 'CUS', label: 'Cuscatlán' },
      { value: 'LAUN', label: 'La Unión' },
      { value: 'VAL', label: 'San Vicente' },
      { value: 'SANTA', label: 'Santa Ana' },
      { value: 'MOR', label: 'Morazán' },
      { value: 'USUL', label: 'Usulután' },
      { value: 'NAV', label: 'Navarra' },
      { value: 'AQU', label: 'Aquirre' },
      { value: 'GRA', label: 'Grabo' },
      { value: 'TIT', label: 'Titlan' },
      { value: 'SAMP', label: 'San Pedro' },
      { value: 'ORM', label: 'Oro' },
      { value: 'GUA', label: 'Guacaat' },
      { value: 'SYN', label: 'Syncott' },
      { value: 'LIS', label: 'Liven' },
      { value: 'NEPT', label: 'Neptune' },
      { value: 'COL', label: 'Colima' },
      { value: 'TRUX', label: 'Truxount' },
    ],
  
    // Guinea Ecuatorial
    GQ: [
      { value: 'MAL', label: 'Malabo' },
      { value: 'BATA', label: 'Bata' },
      { value: 'CONT', label: 'Concordia' },
      { value: 'ANIS', label: 'Anis' },
      { value: 'AQU', label: 'Acuario' },
      { value: 'BAN', label: 'Baniambó' },
      { value: 'EKAT', label: 'Ekat' },
      { value: 'EBO', label: 'Ebebiyin' },
      { value: 'OLO', label: 'Olón' },
      { value: 'UKO', label: 'Ukok' },
      { value: 'GIG', label: 'Gigney' },
      { value: 'CAPE', label: 'Cabo Century' },
      { value: 'SFO', label: 'Sfo' },
      { value: 'FAM', label: 'Fam' },
      { value: 'EGS', label: 'Ege' },
      { value: 'PAM', label: 'Pama' },
      { value: 'SAB', label: 'Sablon' },
      { value: 'BATE', label: 'Batebu' },
      { value: 'NCH', label: 'Nchar' },
      { value: 'OMGA', label: 'Omunga' },
      { value: 'MIC', label: 'Migag' },
    ],
  
    // Eritrea
    ER: [
      { value: 'ASM', label: 'Asmara' },
      { value: 'MAH', label: 'Mahl Bihr' },
      { value: 'KIR', label: 'Kirk' },
      { value: 'KIG', label: 'Kigalle' },
      { value: 'GAS', label: 'Gash-Barka' },
      { value: 'SENT', label: 'Senafe' },
      { value: 'MEL', label: 'Mai-Mene' },
      { value: 'AGG', label: 'Ageisha' },
      { value: 'TAL', label: 'Talos' },
      { value: 'ZAG', label: 'Zagazig' },
      { value: 'MOL', label: 'Molato' },
      { value: 'ZAL', label: 'Zalan' },
      { value: 'DALO', label: 'Dalo' },
      { value: 'FUNK', label: 'Funk' },
      { value: 'MUH', label: 'Muhara' },
      { value: 'DEHA', label: 'Dehai' },
      { value: 'HARI', label: 'Harib' },
      { value: 'EROM', label: 'Erom' },
      { value: 'NEGL', label: 'Neglik' },
      { value: 'SELB', label: 'Selab' },
      { value: 'SAND', label: 'Sand' },
    ],
  
    // Estonia
    EE: [
      { value: 'TAL', label: 'Tallin' },
      { value: 'TART', label: 'Tartu' },
      { value: 'PARN', label: 'Pärnu' },
      { value: 'NAR', label: 'Narva' },
      { value: 'VILJ', label: 'Viljandi' },
      { value: 'KOHT', label: 'Kohtla-Järve' },
      { value: 'HAAR', label: 'Haarla' },
      { value: 'KURE', label: 'Kuremaa' },
      { value: 'VÄX', label: 'Väike-Maarja' },
      { value: 'URD', label: 'Urdova' },
      { value: 'OTI', label: 'Otina' },
      { value: 'SAND', label: 'Sand' },
      { value: 'LAG', label: 'Laagri' },
      { value: 'TUG', label: 'Tugva' },
      { value: 'SAPA', label: 'Sapir' },
      { value: 'MEGA', label: 'Meggen' },
      { value: 'MUHA', label: 'Muhusa' },
      { value: 'MAAO', label: 'Maroosa' },
      { value: 'VAL', label: 'Valga' },
      { value: 'HAGE', label: 'Häga' },
    ],
  
    // Etiopía
    ET: [
      { value: 'ADD', label: 'Adís Abeba' },
      { value: 'OROMI', label: 'Oromía' },
      { value: 'AFA', label: 'Afar' },
      { value: 'TIGRAY', label: 'Tigray' },
      { value: 'BENI', label: 'Benishangul-Gumuz' },
      { value: 'HARE', label: 'Harari' },
      { value: 'GAMB', label: 'Gambela' },
      { value: 'SNNP', label: 'Naciones del Sur, Nacionalidades y Pueblos' },
      { value: 'DIRE', label: 'Dire Dawa' },
      { value: 'KUA', label: 'Kuala Lumpur' },
      { value: 'SEL', label: 'Selangor' },
      { value: 'JHR', label: 'Johor' },
      { value: 'PIN', label: 'Penang' },
      { value: 'PER', label: 'Perak' },
      { value: 'MAL', label: 'Malacca' },
      { value: 'KED', label: 'Kedah' },
      { value: 'KEL', label: 'Kelantan' },
      { value: 'NGA', label: 'Negeri Sembilan' },
      { value: 'PRA', label: 'Perlis' },
      { value: 'SAB', label: 'Sabah' },
      { value: 'SAR', label: 'Sarawak' },
      { value: 'WIL', label: 'Wilayah Persekutuan' },
      { value: 'TUA', label: 'Tuaran' },
      { value: 'KUCH', label: 'Kuching' },
      { value: 'KAL', label: 'Klang' },
      { value: 'BER', label: 'Bermuda' },
      { value: 'LANG', label: 'Langkawi' },
      { value: 'KED', label: 'Kedah' },
      { value: 'OSU', label: 'Osh' },
      { value: 'PER', label: 'Perlis' },
    ],
  
    // Malaui
    MW: [
      { value: 'LIL', label: 'Lilongwe' },
      { value: 'BLAN', label: 'Blantyre' },
      { value: 'MUL', label: 'Muloza' },
      { value: 'NKT', label: 'Nkhotakota' },
      { value: 'KAR', label: 'Karonga' },
      { value: 'PHO', label: 'Phalombe' },
      { value: 'CHIM', label: 'Chitipa' },
      { value: 'DITA', label: 'Dita' },
      { value: 'ZOM', label: 'Zomba' },
      { value: 'MCH', label: 'Mchinji' },
      { value: 'MANG', label: 'Mangochi' },
      { value: 'NTCH', label: 'Ntchisi' },
      { value: 'NYA', label: 'Nyasa' },
      { value: 'NKH', label: 'Nkhata Bay' },
      { value: 'NKH', label: 'Nkhotakota' },
      { value: 'ZOM', label: 'Zomba' },
      { value: 'LIM', label: 'Limbe' },
      { value: 'MAT', label: 'Matola' },
      { value: 'MAK', label: 'Makokola' },
      { value: 'KAS', label: 'Kasungu' },
      { value: 'NAS', label: 'Nassau' },
    ],
  
    // Malasia
    MY: [
      { value: 'KUALA', label: 'Kuala Lumpur' },
      { value: 'SEL', label: 'Selangor' },
      { value: 'JOH', label: 'Johor' },
      { value: 'PEN', label: 'Penang' },
      { value: 'PER', label: 'Perak' },
      { value: 'MAL', label: 'Malacca' },
      { value: 'KED', label: 'Kedah' },
      { value: 'KEL', label: 'Kelantan' },
      { value: 'NEG', label: 'Negeri Sembilan' },
      { value: 'PERLIS', label: 'Perlis' },
      { value: 'SABAH', label: 'Sabah' },
      { value: 'SARAWAK', label: 'Sarawak' },
      { value: 'FED', label: 'Federal Territory of Kuala Lumpur' },
      { value: 'LANG', label: 'Langkawi' },
      { value: 'BENT', label: 'Bentong' },
      { value: 'KAP', label: 'Kampung' },
      { value: 'PASIR', label: 'Pasir Mas' },
      { value: 'OSUN', label: 'Osun' },
      { value: 'KANG', label: 'Kangaroo' },
      { value: 'KAL', label: 'Kelantan' },
      { value: 'SELANGOR', label: 'Selangor' },
    ],
  
    // Maldivas
    MV: [
      { value: 'MAL', label: 'Malé' },
      { value: 'ADU', label: 'Addu City' },
      { value: 'GAF', label: 'Gafaru' },
      { value: 'BAA', label: 'Baa Atoll' },
      { value: 'THAA', label: 'Thaa Atoll' },
      { value: 'KAA', label: 'Kaa Atoll' },
    ],
  
    // Mali
    ML: [
      { value: 'BAM', label: 'Bamako' },
      { value: 'SEG', label: 'Segou' },
      { value: 'KADI', label: 'Kadiogo' },
      { value: 'GAO', label: 'Gao' },
      { value: 'MOP', label: 'Mopti' },
      { value: 'SIK', label: 'Sikasso' },
      { value: 'KOU', label: 'Koulikoro' },
      { value: 'TOM', label: 'Tombouctou' },
      { value: 'KID', label: 'Kidal' },
      { value: 'SANK', label: 'Sankore' },
      { value: 'CIRE', label: 'Ciré' },
      { value: 'FALA', label: 'Faladié' },
      { value: 'BAD', label: 'Badalabougou' },
      { value: 'KIRE', label: 'Kireker' },
    ],
  
    // Malta
    MT: [
      { value: 'VAL', label: 'Valletta' },
      { value: 'MDN', label: 'Mosta' },
      { value: 'Sli', label: 'Sliema' },
      { value: 'BIRK', label: 'Birkirkara' },
      { value: 'RAB', label: 'Rabat' },
      { value: 'QRM', label: 'Qormi' },
      { value: 'MEL', label: 'Mellieħa' },
      { value: 'MAR', label: 'Marsaskala' },
      { value: 'ZWZ', label: 'Zwejj' },
      { value: 'GOZ', label: 'Gozo' },
    ],
  
    // Marruecos
    MA: [
      { value: 'RAB', label: 'Rabat' },
      { value: 'CAS', label: 'Casablanca' },
      { value: 'FEZ', label: 'Fez' },
      { value: 'TAN', label: 'Tánger' },
      { value: 'MARR', label: 'Marrakech' },
      { value: 'AGAD', label: 'Agadir' },
      { value: 'KEC', label: 'Kenitra' },
      { value: 'TET', label: 'Tétouan' },
      { value: 'ESS', label: 'Essaouira' },
      { value: 'SLA', label: 'Salé' },
      { value: 'KHEN', label: 'Khenifra' },
      { value: 'AZI', label: 'Azilal' },
      { value: 'MUL', label: 'Moulouya' },
      { value: 'OUJ', label: 'Oujda' },
      { value: 'MUNI', label: 'Munjiz' },
      { value: 'TAZ', label: 'Taza' },
    ],
  
    // Mozambique
    MZ: [
      { value: 'MAP', label: 'Maputo' },
      { value: 'NAMP', label: 'Nampula' },
      { value: 'BEIRA', label: 'Beira' },
      { value: 'MIAT', label: 'Matola' },
      { value: 'TET', label: 'Tete' },
      { value: 'INHAM', label: 'Inhambane' },
      { value: 'GAZ', label: 'Gaza' },
      { value: 'ZAM', label: 'Zambezia' },
      { value: 'MAPUTO', label: 'Maputo' },
      { value: 'CAIA', label: 'Caia' },
    ],
  
    // Namibia
    NA: [
      { value: 'WIND', label: 'Windhoek' },
      { value: 'SWAK', label: 'Swakopmund' },
      { value: 'KHOR', label: 'Khorixas' },
      { value: 'OKA', label: 'Okahandja' },
      { value: 'TWI', label: 'Twyfelfontein' },
      { value: 'KAV', label: 'Kavango' },
      { value: 'ERF', label: 'Erongo' },
      { value: 'OMU', label: 'Omusati' },
      { value: 'OHANG', label: 'Ohangwena' },
      { value: 'ZAMB', label: 'Zambezi' },
    ],
  
    // Nauru
    NR: [
      { value: 'YAREN', label: 'Yaren' },
      { value: 'ALEC', label: 'Anabar' },
      { value: 'BUI', label: 'Boe' },
      { value: 'NAP', label: 'Napu' },
      { value: 'NIN', label: 'Ninning' },
    ],
  
    // Nepal
    NP: [
      { value: 'KTM', label: 'Catmandú' },
      { value: 'BHA', label: 'Bhaktapur' },
      { value: 'LAL', label: 'Lalitpur' },
      { value: 'POK', label: 'Pokhara' },
      { value: 'DOL', label: 'Dolakha' },
      { value: 'BARA', label: 'Bardiya' },
      { value: 'SIND', label: 'Sindhupalchok' },
      { value: 'GAR', label: 'Gorkha' },
      { value: 'UML', label: 'Udayapur' },
      { value: 'NAR', label: 'Narayani' },
    ],
  
    // Países Bajos
    NL: [
      { value: 'AMS', label: 'Ámsterdam' },
      { value: 'ROT', label: 'Róterdam' },
      { value: 'THE', label: 'La Haya' },
      { value: 'UTR', label: 'Utrecht' },
      { value: 'EIND', label: 'Eindhoven' },
      { value: 'GRON', label: 'Groninga' },
      { value: 'DORD', label: 'Dordrecht' },
      { value: 'NOORD', label: 'Noord-Holland' },
      { value: 'ZUID', label: 'Zuid-Holland' },
      { value: 'GEL', label: 'Gelderland' },
    ],
  
    // Nueva Zelanda
    NZ: [
      { value: 'AKL', label: 'Auckland' },
      { value: 'WLG', label: 'Wellington' },
      { value: 'CHC', label: 'Christchurch' },
      { value: 'HAMIL', label: 'Hamilton' },
      { value: 'DUN', label: 'Dunedin' },
      { value: 'TGA', label: 'Tauranga' },
      { value: 'NAPIER', label: 'Napier' },
      { value: 'ROTOR', label: 'Rotorua' },
      { value: 'WHK', label: 'Whakatane' },
      { value: 'BLEN', label: 'Blenheim' },
    ],
  
    // Nicaragua
    NI: [
      { value: 'MAN', label: 'Managua' },
      { value: 'LEON', label: 'León' },
      { value: 'MADR', label: 'Masaya' },
      { value: 'CHIN', label: 'Chinandega' },
      { value: 'RIVAS', label: 'Rivas' },
      { value: 'ESTEL', label: 'Estelí' },
      { value: 'MATAG', label: 'Matagalpa' },
      { value: 'SOM', label: 'Somoto' },
      { value: 'JINOTE', label: 'Jinotega' },
      { value: 'CUN', label: 'Cuneta' },
    ],
  
    // Níger
    NE: [
      { value: 'NIAMEY', label: 'Niamey' },
      { value: 'MARADI', label: 'Maradi' },
      { value: 'KAYES', label: 'Kaya' },
      { value: 'TILL', label: 'Tillabéri' },
      { value: 'ZINDER', label: 'Zinder' },
      { value: 'DOSSO', label: 'Dosso' },
      { value: 'TIL', label: 'Tiliou' },
      { value: 'GIZ', label: 'Giza' },
      { value: 'DIFFA', label: 'Diffa' },
      { value: 'TATE', label: 'Tata' },
    ],
  
    // Nigeria
    NG: [
      { value: 'ABU', label: 'Abuja (Territorio de la Capital)' },
      { value: 'LAG', label: 'Lagos' },
      { value: 'IBADAN', label: 'Ibadan' },
      { value: 'KAD', label: 'Kaduna' },
      { value: 'PORTH', label: 'Port Harcourt' },
      { value: 'BAUCHI', label: 'Bauchi' },
      { value: 'ONDO', label: 'Ondo' },
      { value: 'ABIA', label: 'Abia' },
      { value: 'ENUGU', label: 'Enugu' },
      { value: 'IKOR', label: 'Ikorodu' },
      { value: 'EKO', label: 'Eko' },
      { value: 'EPE', label: 'Epe' },
      { value: 'BIR', label: 'Birnin' },
      { value: 'SOLO', label: 'Solve' },
      { value: 'SAT', label: 'Satall' },
      { value: 'UGA', label: 'Uwad' },
      { value: 'HERS', label: 'Hersal' },
      { value: 'BOSE', label: 'Boset' },
      { value: 'OBA', label: 'Oban' },
      { value: 'OLO', label: 'Olu' },
    ],
  
    // Omán
    OM: [
      { value: 'MUS', label: 'Mascate' },
      { value: 'DHA', label: 'Dhofar' },
      { value: 'ALB', label: 'Al Batinah' },
      { value: 'ALD', label: 'Al Dhahirah' },
      { value: 'ALSH', label: 'Al Sharquiyah' },
      { value: 'MAN', label: 'Manah' },
      { value: 'MUQ', label: 'Muqshin' },
      { value: 'NAQ', label: 'Nizwa' },
      { value: 'SYN', label: 'Syna' },
      { value: 'SHIHR', label: 'Shahrak' },
    ],
  
    // Pakistán
    PK: [
      { value: 'ISB', label: 'Islamabad' },
      { value: 'KAR', label: 'Karachi' },
      { value: 'LHE', label: 'Lahore' },
      { value: 'PES', label: 'Peshawar' },
      { value: 'QUET', label: 'Quetta' },
      { value: 'FAIS', label: 'Faisalabad' },
      { value: 'MULT', label: 'Multan' },
      { value: 'SUKK', label: 'Sukkur' },
      { value: 'RAW', label: 'Rawalpindi' },
      { value: 'GWD', label: 'Gujranwala' },
      { value: 'MAN', label: 'Mandi Bahauddin' },
    ],
  
    // Palau
    PW: [
      { value: 'NGER', label: 'Ngerulmud' },
      { value: 'MELEKE', label: 'Melekeok' },
      { value: 'BABEL', label: 'Babeldaob' },
      { value: 'ANG', label: 'Angaur' },
      { value: 'KOROR', label: 'Koror' },
      { value: 'PTO', label: 'Pto' },
      { value: 'AR', label: 'Aruerong' },
    ],
  
    // Panamá
    PA: [
      { value: 'PAN', label: 'Ciudad de Panamá' },
      { value: 'COL', label: 'Colón' },
      { value: 'CHIRA', label: 'Chiriquí' },
      { value: 'BOK', label: 'Bocas del Toro' },
      { value: 'DARI', label: 'Darién' },
      { value: 'HERR', label: 'Herrera' },
      { value: 'LOS', label: 'Los Santos' },
      { value: 'PAN', label: 'Panamá Oeste' },
      { value: 'GUNA', label: 'Guna Yala' },
    ],
  
    // Paraguay
    PY: [
      { value: 'ASN', label: 'Asunción' },
      { value: 'PAR', label: 'Paraguari' },
      { value: 'CANA', label: 'Canindeyú' },
      { value: 'ALTO', label: 'Alto Paraná' },
      { value: 'ITAP', label: 'Itapúa' },
      { value: 'CUE', label: 'Cordillera' },
      { value: 'AMAM', label: 'Amambay' },
      { value: 'PRES', label: 'Presidente Hayes' },
      { value: 'CONCE', label: 'Concepción' },
      { value: 'CUS', label: 'Caaguazú' },
      { value: 'ALTO', label: 'Alto Paraguay' },
    ],
  
    // Perú
    PE: [
      { value: 'LIM', label: 'Lima' },
      { value: 'ARE', label: 'Arequipa' },
      { value: 'CUS', label: 'Cusco' },
      { value: 'TRUJ', label: 'Trujillo' },
      { value: 'LAMB', label: 'Lambayeque' },
      { value: 'PIURA', label: 'Piura' },
      { value: 'CALL', label: 'Callao' },
      { value: 'HUA', label: 'Huancayo' },
      { value: 'TAC', label: 'Tacna' },
      { value: 'JUN', label: 'Junín' },
      { value: 'JUL', label: 'Juliaca' },
    ],
  
    // Filipinas
    PH: [
      { value: 'MAN', label: 'Manila' },
      { value: 'QUE', label: 'Quezon City' },
      { value: 'DAVA', label: 'Davao City' },
      { value: 'CEBU', label: 'Cebu City' },
      { value: 'ZAM', label: 'Zamboanga City' },
      { value: 'ANTIQUE', label: 'Antique' },
      { value: 'LAY', label: 'Laoag' },
      { value: 'PANG', label: 'Pangasinan' },
      { value: 'BAT', label: 'Batangas' },
      { value: 'BENG', label: 'Benguet' },
      { value: 'LAG', label: 'Laguna' },
      { value: 'ILOC', label: 'Ilocos Norte' },
      { value: 'NEVA', label: 'Nueva Ecija' },
      { value: 'BOHOL', label: 'Bohol' },
      { value: 'KAL', label: 'Kalibo' },
      { value: 'MIND', label: 'Mindanao' },
      { value: 'BE', label: 'Bohol' },
      { value: 'BATANG', label: 'Batangas' },
      { value: 'LAGA', label: 'Laguna' },
      { value: 'KAPL', label: 'Kapamilya' },
      { value: 'ZAMBO', label: 'Zamboanga' },
    ],
  
    // Portugal
    PT: [
      { value: 'LIS', label: 'Lisboa' },
      { value: 'OPO', label: 'Porto' },
      { value: 'AMAD', label: 'Amadora' },
      { value: 'AVEIRO', label: 'Aveiro' },
      { value: 'BEC', label: 'Beja' },
      { value: 'PORT', label: 'Portalegre' },
      { value: 'LEIRIA', label: 'Leiria' },
      { value: 'BRAG', label: 'Bragança' },
      { value: 'FARO', label: 'Faro' },
      { value: 'ÉVORA', label: 'Évora' },
      { value: 'SANT', label: 'Santarém' },
      { value: 'SET ', label: 'Setúbal' },
      { value: 'VIA', label: 'Viana do Castelo' },
      { value: 'COIM', label: 'Coimbra' },
      { value: 'LEI', label: 'Leiria' },
      { value: 'SCO', label: 'Setúbal' },
      { value: 'AÇOR', label: 'Açores' },
      { value: 'MADE', label: 'Madeira' },
      { value: 'BEI', label: 'Beira Interior Norte' },
      { value: 'AL', label: 'Alentejo' },
    ],
  
    // Catar
    QA: [
      { value: 'DOHA', label: 'Doha' },
      { value: 'AL-W', label: 'Al Wakrah' },
      { value: 'MUSHA', label: 'Mushayrib' },
      { value: 'AL-K', label: 'Al Khawr' },
      { value: 'ADDAI', label: 'Al Daayen' },
      { value: 'AQD', label: 'Al Gharafa' },
      { value: 'AL-KA', label: 'Al Khor' },
      { value: 'AL-W', label: 'Al Wukair' },
      { value: 'UMM', label: 'Umm Salal' },
    ],
  
    // República Checa
    CZ: [
      { value: 'PRA', label: 'Praga' },
      { value: 'BRNO', label: 'Brno' },
      { value: 'OST', label: 'Ostrava' },
      { value: 'PLZEN', label: 'Plzeň' },
      { value: 'LIB', label: 'Liberec' },
      { value: 'UST', label: 'Ústí nad Labem' },
      { value: 'HRA', label: 'Hradec Králové' },
      { value: 'ZLIN', label: 'Zlín' },
      { value: 'KAR', label: 'Karlovy Vary' },
      { value: 'VYS', label: 'Vysočina' },
    ],
  
    // Rumanía
    RO: [
      { value: 'BUC', label: 'Bucarest' },
      { value: 'CLUJ', label: 'Cluj-Napoca' },
      { value: 'TIMI', label: 'Timișoara' },
      { value: 'CFR', label: 'Craiova' },
      { value: 'IASI', label: 'Iași' },
      { value: 'BRA', label: 'Brașov' },
      { value: 'GAL', label: 'Galați' },
      { value: 'PIT', label: 'Pitești' },
      { value: 'SUCE', label: 'Suceava' },
      { value: 'BAC', label: 'Bacău' },
    ],
  
    // Rusia
    RU: [
      { value: 'MOS', label: 'Moscú' },
      { value: 'SAN', label: 'San Petersburgo' },
      { value: 'NOVOS', label: 'Novosibirsk' },
      { value: 'EKAT', label: 'Ekaterimburgo' },
      { value: 'NIZH', label: 'Nizhni Nóvgorod' },
      { value: 'KAZAN', label: 'Kazan' },
      { value: 'CHE', label: 'Chelyabinsk' },
      { value: 'SAM', label: 'Samara' },
      { value: 'ROST', label: 'Rostov del Don' },
      { value: 'TULA', label: 'Tula' },
    ],
  
    // Ruanda
    RW: [
      { value: 'KIG', label: 'Kigali' },
      { value: 'BUT', label: 'Butare' },
      { value: 'GIK', label: 'Gikongoro' },
      { value: 'BYUM', label: 'Byumba' },
      { value: 'NGOMA', label: 'Ngoma' },
      { value: 'KIH', label: 'Kihihi' },
      { value: 'NYA', label: 'Nyamasheke' },
      { value: 'NYUNGWE', label: 'Nyungwe' },
      { value: 'CAN', label: 'Canari' },
      { value: 'RUY', label: 'Ruyigi' },
    ],
  
    // Senegal
    SN: [
      { value: 'DAK', label: 'Dakar' },
      { value: 'THIES', label: 'Thiès' },
      { value: 'DIO', label: 'Diourbel' },
      { value: 'KAF', label: 'Kaffrine' },
      { value: 'MBO', label: 'Mbour' },
      { value: 'SAK', label: 'Sakassou' },
      { value: 'TAMB', label: 'Tambacounda' },
      { value: 'KOL', label: 'Kolda' },
      { value: 'ZIG', label: 'Ziguinchor' },
      { value: 'MAT', label: 'Matam' },
    ],
  
    // Serbia
    RS: [
      { value: 'BEL', label: 'Belgrado' },
      { value: 'NIS', label: 'Niš' },
      { value: 'NOVI', label: 'Novi Sad' },
      { value: 'UESTRAF', label: 'Užice' },
      { value: 'SAB', label: 'Sabac' },
      { value: 'TOV', label: 'Tovarnik' },
      { value: 'VAL', label: 'Valjevo' },
      { value: 'VRS', label: 'Vrsac' },
      { value: 'HUM', label: 'Humba' },
      { value: 'ZLAT', label: 'Zlatibor' },
    ],
  
    // Singapur
    SG: [
      { value: 'CCK', label: 'Changi' },
      { value: 'GRT', label: 'Geylang' },
      { value: 'MAR', label: 'Marine Parade' },
      { value: 'TAMP', label: 'Tampines' },
      { value: 'YISHUN', label: 'Yishun' },
      { value: 'BUK', label: 'Bukit Merah' },
      { value: 'JUR', label: 'Jurong West' },
      { value: 'HOU', label: 'Hougang' },
      { value: 'RED', label: 'Redhill' },
      { value: 'MING', label: 'Ming' },
    ],
  
    // Siria
    SY: [
      { value: 'DAM', label: 'Damasco' },
      { value: 'ALEP', label: 'Alepo' },
      { value: 'HOMS', label: 'Homs' },
      { value: 'LAT', label: 'Latakia' },
      { value: 'TART', label: 'Tartus' },
      { value: 'DAR', label: 'Daraa' },
      { value: 'RAQ', label: 'Raqa' },
      { value: 'HASS', label: 'Hassake' },
      { value: 'DEIR', label: 'Deir ez-Zor' },
      { value: 'QUNE', label: 'Quneitra' },
    ],
  
    // Suecia
    SE: [
      { value: 'STOCK', label: 'Estocolmo' },
      { value: 'GOT', label: 'Gotemburgo' },
      { value: 'MALM', label: 'Malmö' },
      { value: 'UPPS', label: 'Uppsala' },
      { value: 'VÄXJ', label: 'Växjö' },
      { value: 'SÖDER', label: 'Södertälje' },
      { value: 'JÖK', label: 'Jönköping' },
      { value: 'LUND', label: 'Lund' },
      { value: 'GNES', label: 'Gnesio' },
      { value: 'SKÄ', label: 'Skåne' },
    ],
  
    // Suiza
    CH: [
      { value: 'BER', label: 'Berna' },
      { value: 'ZUR', label: 'Zúrich' },
      { value: 'GEN', label: 'Ginebra' },
      { value: 'BAS', label: 'Basilea' },
      { value: 'LAUS', label: 'Lausana' },
      { value: 'LUC', label: 'Lucerna' },
      { value: 'NEUCH', label: 'Neuchâtel' },
      { value: 'FRI', label: 'Friburgo' },
      { value: 'ZUG', label: 'Zug' },
      { value: 'SOLO', label: 'Soloturno' },
    ],
  
    // Tailandia
    TH: [
      { value: 'BKK', label: 'Bangkok' },
      { value: 'CHI', label: 'Chiang Mai' },
      { value: 'PHUK', label: 'Phuket' },
      { value: 'NONG', label: 'Nong Khai' },
      { value: 'SURA', label: 'Surat Thani' },
      { value: 'NAKH', label: 'Nakhon Ratchasima' },
      { value: 'AYUT', label: 'Ayutthaya' },
      { value: 'PATHUM', label: 'Pathum Thani' },
      { value: 'RAY', label: 'Rayong' },
      { value: 'SAK', label: 'Sakonnakhon' },
    ],
  
    // Taiwán
    TW: [
      { value: 'TAI', label: 'Taipéi' },
      { value: 'KAO', label: 'Kaohsiung' },
      { value: 'TAN', label: 'Tainan' },
      { value: 'TAI', label: 'Taichung' },
      { value: 'HUAL', label: 'Hualien' },
      { value: 'CHIY', label: 'Chiayi' },
      { value: 'PEN', label: 'Penghu' },
      { value: 'TIA', label: 'Taitung' },
      { value: 'NANT', label: 'Nantou' },
      { value: 'YUN', label: 'Yunlin' },
    ],
  
    // Tanzania
    TZ: [
      { value: 'DAR', label: 'Dar es Salaam' },
      { value: 'ARUS', label: 'Arusha' },
      { value: 'DODOMA', label: 'Dodoma' },
      { value: 'KIG', label: 'Kigoma' },
      { value: 'TAB', label: 'Tabora' },
      { value: 'NZ', label: 'Njombe' },
      { value: 'SHIN', label: 'Shinyanga' },
      { value: 'KIL', label: 'Kilimanjaro' },
      { value: 'MARA', label: 'Mara' },
      { value: 'MAR', label: 'Mbeya' },
    ],
  
    // Timor Oriental
    TL: [
      { value: 'DILI', label: 'Dili' },
      { value: 'BAU', label: 'Baucau' },
      { value: 'AILEU', label: 'Aileu' },
      { value: 'ALIE', label: 'Alieu' },
      { value: 'OEC', label: 'Oecusse' },
      { value: 'LAUT', label: 'Lautem' },
      { value: 'MAN', label: 'Manatuto' },
      { value: 'VIK', label: 'Viqueque' },
      { value: 'DILI', label: 'Dili' },
      { value: 'MANT', label: 'Manatuto' },
    ],
  
    // Togo
    TG: [
      { value: 'LOME', label: 'Lomé' },
      { value: 'TSE', label: 'Tsevie' },
      { value: 'KARA', label: 'Kara' },
      { value: 'PLATE', label: 'Plateau' },
      { value: 'REG', label: 'Region Centrale' },
      { value: 'BAS', label: 'Bas-Mono' },
      { value: 'PRET', label: 'Préfecture de Blitta' },
      { value: 'KOT', label: 'Koto' },
      { value: 'SAV', label: 'Savanes' },
      { value: 'MOA', label: 'Moatakefe' },
    ],
  
    // Tonga
    TO: [
      { value: 'NUK', label: 'Nukualofa' },
      { value: 'VAVA', label: 'Vavau' },
      { value: 'HAA', label: 'Haapai' },
      { value: 'NIA', label: 'Niuafoʻou' },
      { value: 'NUI', label: 'Niuatoputapu' },
      { value: 'TON', label: 'Tongatapu' },
    ],
  
    // Túnez
    TN: [
      { value: 'TUN', label: 'Túnez' },
      { value: 'SUS', label: 'Sousse' },
      { value: 'AFO', label: 'Ariana' },
      { value: 'BEJA', label: 'Béja' },
      { value: 'KAF', label: 'Kasserine' },
      { value: 'SAH', label: 'Sahara' },
      { value: 'NOUM', label: 'Nabeul' },
      { value: 'SAH', label: 'Salah' },
      { value: 'ZAM', label: 'Zaghouan' },
      { value: 'KAIROUAN', label: 'Kairouan' },
    ],
  
    // Turkmenistán
    TM: [
      { value: 'ASH', label: 'Asjabad' },
      { value: 'MAR', label: 'Mary' },
      { value: 'DASH', label: 'Daşoguz' },
      { value: 'LON', label: 'Loncar' },
      { value: 'KEL', label: 'Kelkit' },
      { value: 'BALK', label: 'Balkanabat' },
      { value: 'LEKAN', label: 'Lekan' },
      { value: 'GEL', label: 'Gelen' },
      { value: 'KARA', label: 'Kara-Kalpak' },
    ],
  
    // Ucrania
    UA: [
      { value: 'KYI', label: 'Kiev' },
      { value: 'KHARK', label: 'Járkov' },
      { value: 'ODES', label: 'Odessa' },
      { value: 'DN', label: 'Dnipró' },
      { value: 'ZAP', label: 'Zaporiyia' },
      { value: 'LVIV', label: 'Leópolis' },
      { value: 'RIVN', label: 'Rovno' },
      { value: 'POL', label: 'Poltava' },
      { value: 'VIN', label: 'Vinnytsia' },
      { value: 'JK', label: 'Zhytomyr' },
    ],
  
    // Emiratos Árabes Unidos
    AE: [
      { value: 'ABU', label: 'Abu Dabi' },
      { value: 'DUB', label: 'Dubái' },
      { value: 'SHARJ', label: 'Sharjah' },
      { value: 'AJMAN', label: 'Ajmán' },
      { value: 'FUJ', label: 'Fujairah' },
      { value: 'RAK', label: 'Ras al-Jaima' },
      { value: 'UMM', label: 'Umm al-Quwain' },
      { value: 'DHA', label: 'Al Dhafra' },
      { value: 'AL-AIN', label: 'Al Ain' },
      { value: 'LIB', label: 'Líbano' },
    ],
  
    // Reino Unido
    GB: [
      { value: 'LON', label: 'Londres' },
      { value: 'BIR', label: 'Birminghame' },
      { value: 'MANC', label: 'Mánchester' },
      { value: 'LIV', label: 'Liverpool' },
      { value: 'GLAS', label: 'Glasgow' },
      { value: 'BRIS', label: 'Bristol' },
      { value: 'BATE', label: 'Bath' },
      { value: 'COV', label: 'Coventry' },
      { value: 'LEIC', label: 'Leicester' },
      { value: 'EDIN', label: 'Edimburgo' },
      { value: 'SHEFF', label: 'Sheffield' },
      { value: 'NOTT', label: 'Nottingham' },
      { value: 'NEW', label: 'Newcastle' },
      { value: 'CARD', label: 'Cardiff' },
      { value: 'BEL', label: 'Belfast' },
      { value: 'LIVER', label: 'Liverpol' },
      { value: 'NORW', label: 'Norwich' },
      { value: 'LEWI', label: 'Lewis' },
      { value: 'WEL', label: 'Waltham' },
      { value: 'SAND', label: 'Sandwich' },
    ],
  
    // Estados Unidos
    US: [
      { value: 'WA', label: 'Washington' },
      { value: 'CA', label: 'California' },
      { value: 'NY', label: 'New York' },
      { value: 'TX', label: 'Texas' },
      { value: 'FL', label: 'Florida' },
      { value: 'IL', label: 'Illinois' },
      { value: 'PA', label: 'Pensilvania' },
      { value: 'OH', label: 'Ohio' },
      { value: 'GA', label: 'Georgia' },
      { value: 'MI', label: 'Míchigan' },
      { value: 'NC', label: 'Carolina del Norte' },
      { value: 'NJ', label: 'Nueva Jersey' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'IN', label: 'Indiana' },
      { value: 'MO', label: 'Misuri' },
      { value: 'MD', label: 'Maryland' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'WA', label: 'Washington D.C.' },
    ],
  
    // Uruguay
    UY: [
      { value: 'MON', label: 'Montevideo' },
      { value: 'CANA', label: 'Canelones' },
      { value: 'DUR', label: 'Durazno' },
      { value: 'SAL', label: 'Salto' },
      { value: 'PAYS', label: 'Paysandú' },
      { value: 'SAN', label: 'San José' },
      { value: 'RIV', label: 'Rivera' },
      { value: 'TACU', label: 'Tacuarembó' },
      { value: 'ART', label: 'Artigas' },
      { value: 'DOL', label: 'Dolores' },
    ],
  
    // Venezuela
    VE: [
      { value: 'CAR', label: 'Caracas' },
      { value: 'ZUL', label: 'Zulia' },
      { value: 'ANZO', label: 'Anzoátegui' },
      { value: 'LARA', label: 'Lara' },
      { value: 'FAL', label: 'Falcón' },
      { value: 'MIR', label: 'Miranda' },
      { value: 'MON', label: 'Monagas' },
      { value: 'TRU', label: 'Trujillo' },
      { value: 'DEP', label: 'Dependencias Federales' },
      { value: 'TACH', label: 'Táchira' },
      { value: 'GUAR', label: 'Guárico' },
    ],
  
    // Vietnam
    VN: [
      { value: 'HANOI', label: 'Hanoi' },
      { value: 'HOCH', label: 'Ciudad Ho Chi Minh' },
      { value: 'DA', label: 'Da Nang' },
      { value: 'NHA', label: 'Nha Trang' },
      { value: 'HAIPH', label: 'Hai Phong' },
      { value: 'THANH', label: 'Thanh Hoa' },
      { value: 'DONG', label: 'Dong Nai' },
      { value: 'BINH', label: 'Binh Duong' },
      { value: 'KON', label: 'Kon Tum' },
      { value: 'LAM', label: 'Lam Dong' },
    ],
  };
  
  export const nationalities = [
    { value: '', label: 'Select Nationality' },
    { value: 'American', label: 'American' },
    { value: 'Canadian', label: 'Canadian' },
    { value: 'British', label: 'British' },
    { value: 'Australian', label: 'Australian' },
    { value: 'Indian', label: 'Indian' },
    { value: 'Chinese', label: 'Chinese' },
    { value: 'Japanese', label: 'Japanese' },
    { value: 'Russian', label: 'Russian' },
    { value: 'German', label: 'German' },
    { value: 'French', label: 'French' },
    { value: 'Brazilian', label: 'Brazilian' },
    { value: 'Mexican', label: 'Mexican' },
    { value: 'Nigerian', label: 'Nigerian' },
    { value: 'Bangladeshi', label: 'Bangladeshi' },
    { value: 'Pakistani', label: 'Pakistani' },
    { value: 'Vietnamese', label: 'Vietnamese' },
    { value: 'Egyptian', label: 'Egyptian' },
    { value: 'Turkish', label: 'Turkish' },
    { value: 'Indonesian', label: 'Indonesian' },
    { value: 'Filipino', label: 'Filipino' },
    { value: 'South African', label: 'South African' },
    { value: 'Colombian', label: 'Colombian' },
    { value: 'Argentine', label: 'Argentine' },
    { value: 'Peruvian', label: 'Peruvian' },
    { value: 'Saudi Arabian', label: 'Saudi Arabian' },
    { value: 'Iranian', label: 'Iranian' },
    { value: 'Algerian', label: 'Algerian' },
    { value: 'Moroccan', label: 'Moroccan' },
    { value: 'Nigerian', label: 'Nigerian' },
    { value: 'Kenyan', label: 'Kenyan' },
    { value: 'Ethiopian', label: 'Ethiopian' },
    { value: 'South Sudanese', label: 'South Sudanese' },
    { value: 'Ghanaian', label: 'Ghanaian' },
    { value: 'Nigerian', label: 'Nigerian' },
    { value: 'South African', label: 'South African' },
    { value: 'Egyptian', label: 'Egyptian' },
    { value: 'Moroccan', label: 'Moroccan' },
    { value: 'Algerian', label: 'Algerian' },
    { value: 'Tunisian', label: 'Tunisian' },
    { value: 'Libyan', label: 'Libyan' },
    { value: 'Sudanese', label: 'Sudanese' },
    { value: 'Ethiopian', label: 'Ethiopian' },
    { value: 'Kenyan', label: 'Kenyan' },
    { value: 'Ugandan', label: 'Ugandan' },
    { value: 'Tanzanian', label: 'Tanzanian' },
    { value: 'Congolese', label: 'Congolese' },
    { value: 'Angolan', label: 'Angolan' },
    { value: 'Nigerian', label: 'Nigerian' },
    { value: 'South African', label: 'South African' },
    { value: 'Ghanaian', label: 'Ghanaian' },
    { value: 'Cameroonian', label: 'Cameroonian' },
    { value: 'Gabonese', label: 'Gabonese' },
    { value: 'Equatorial Guinean', label: 'Equatorial Guinean' },
    { value: 'Central African', label: 'Central African' },
    { value: 'Chadian', label: 'Chadian' },
    { value: 'Sudanese', label: 'Sudanese' },
    { value: 'South Sudanese', label: 'South Sudanese' },
    { value: 'Ethiopian', label: 'Ethiopian' },
    { value: 'Eritrean', label: 'Eritrean' },
    { value: 'Somali', label: 'Somali' },
    { value: 'Djiboutian', label: 'Djiboutian' },
    { value: 'Kenyan', label: 'Kenyan' },
    { value: 'Ugandan', label: 'Ugandan' },
    { value: 'Tanzanian', label: 'Tanzanian' },
    { value: 'Burundian', label: 'Burundian' },
    { value: 'Rwandan', label: 'Rwandan' },
    { value: 'Congolese', label: 'Congolese' },
    { value: 'Angolan', label: 'Angolan' },
    { value: 'Zambian', label: 'Zambian' },
    { value: 'Malawian', label: 'Malawian' },
    { value: 'Mozambican', label: 'Mozambican' },
    { value: 'Zimbabwean', label: 'Zimbabwean' },
    { value: 'Botswana', label: 'Botswana' },
    { value: 'Namibian', label: 'Namibian' },
    { value: 'South African', label: 'South African' },
    { value: 'Lesotho', label: 'Lesotho' },
    { value: 'Swazi', label: 'Swazi' },
    // Add more nationalities as needed
  ];
  